/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type EutraLocation struct {


	
	// simple type
 
	

	Tai Tai `json:"tai" yaml:"tai" bson:"tai" mapstructure:"Tai"`
 
	

	IgnoreTai *bool `json:"ignoreTai,omitempty" yaml:"ignoreTai" bson:"ignoreTai" mapstructure:"IgnoreTai"`
 
	

	Ecgi Ecgi `json:"ecgi" yaml:"ecgi" bson:"ecgi" mapstructure:"Ecgi"`
 
	

	IgnoreEcgi *bool `json:"ignoreEcgi,omitempty" yaml:"ignoreEcgi" bson:"ignoreEcgi" mapstructure:"IgnoreEcgi"`
 
	

	AgeOfLocationInformation *int32 `json:"ageOfLocationInformation,omitempty" yaml:"ageOfLocationInformation" bson:"ageOfLocationInformation" mapstructure:"AgeOfLocationInformation"`
 
	

	UeLocationTimestamp *time.Time `json:"ueLocationTimestamp,omitempty" yaml:"ueLocationTimestamp" bson:"ueLocationTimestamp" mapstructure:"UeLocationTimestamp"`
 
	

	GeographicalInformation *string `json:"geographicalInformation,omitempty" yaml:"geographicalInformation" bson:"geographicalInformation" mapstructure:"GeographicalInformation"`
 
	

	GeodeticInformation *string `json:"geodeticInformation,omitempty" yaml:"geodeticInformation" bson:"geodeticInformation" mapstructure:"GeodeticInformation"`
 
	

	GlobalNgenbId *GlobalRanNodeId `json:"globalNgenbId,omitempty" yaml:"globalNgenbId" bson:"globalNgenbId" mapstructure:"GlobalNgenbId"`
 
	

	GlobalENbId *GlobalRanNodeId `json:"globalENbId,omitempty" yaml:"globalENbId" bson:"globalENbId" mapstructure:"GlobalENbId"`
}
