/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DnnInfo struct {


	
	// simple type
 
	

	Dnn string `json:"dnn" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	DefaultDnnIndicator *bool `json:"defaultDnnIndicator,omitempty" yaml:"defaultDnnIndicator" bson:"defaultDnnIndicator" mapstructure:"DefaultDnnIndicator"`
 
	

	LboRoamingAllowed *bool `json:"lboRoamingAllowed,omitempty" yaml:"lboRoamingAllowed" bson:"lboRoamingAllowed" mapstructure:"LboRoamingAllowed"`
 
	

	IwkEpsInd *bool `json:"iwkEpsInd,omitempty" yaml:"iwkEpsInd" bson:"iwkEpsInd" mapstructure:"IwkEpsInd"`
 
	

	DnnBarred *bool `json:"dnnBarred,omitempty" yaml:"dnnBarred" bson:"dnnBarred" mapstructure:"DnnBarred"`
 
	

	InvokeNefInd *bool `json:"invokeNefInd,omitempty" yaml:"invokeNefInd" bson:"invokeNefInd" mapstructure:"InvokeNefInd"`
 
	

	SmfList *[]string `json:"smfList,omitempty" yaml:"smfList" bson:"smfList" mapstructure:"SmfList"`
 
	

	SameSmfInd *bool `json:"sameSmfInd,omitempty" yaml:"sameSmfInd" bson:"sameSmfInd" mapstructure:"SameSmfInd"`
}
