/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PreemptionCapability string
// enum type
// List of PreemptionCapability 
const (
	PREEMPTIONCAPABILITY_NOT_PREEMPT PreemptionCapability = "NOT_PREEMPT"
	PREEMPTIONCAPABILITY_MAY_PREEMPT PreemptionCapability = "MAY_PREEMPT"
)
