/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type NiddInformation struct {


	
	// simple type
 
	

	AfId string `json:"afId" yaml:"afId" bson:"afId" mapstructure:"AfId"`
 
	

	Gpsi *string `json:"gpsi,omitempty" yaml:"gpsi" bson:"gpsi" mapstructure:"Gpsi"`
 
	

	ExtGroupId *string `json:"extGroupId,omitempty" yaml:"extGroupId" bson:"extGroupId" mapstructure:"ExtGroupId"`
}
