/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type TrafficInfluSub struct {


	
	// simple type

	// Each element identifies a DNN. 
	

	Dnns *[]string `json:"dnns,omitempty" yaml:"dnns" bson:"dnns" mapstructure:"Dnns"`

	// Each element identifies a slice. 
	

	Snssais *[]Snssai `json:"snssais,omitempty" yaml:"snssais" bson:"snssais" mapstructure:"Snssais"`

	// Each element identifies a group of users. 
	

	InternalGroupIds *[]string `json:"internalGroupIds,omitempty" yaml:"internalGroupIds" bson:"internalGroupIds" mapstructure:"InternalGroupIds"`

	// Each element identifies the user. 
	

	Supis *[]string `json:"supis,omitempty" yaml:"supis" bson:"supis" mapstructure:"Supis"`
 
	

	NotificationUri string `json:"notificationUri" yaml:"notificationUri" bson:"notificationUri" mapstructure:"NotificationUri"`
 
	

	Expiry *time.Time `json:"expiry,omitempty" yaml:"expiry" bson:"expiry" mapstructure:"Expiry"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
}
