/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PatchOperation string
// enum type
// List of PatchOperation 
const (
	PATCHOPERATION_ADD PatchOperation = "add"
	PATCHOPERATION_COPY PatchOperation = "copy"
	PATCHOPERATION_MOVE PatchOperation = "move"
	PATCHOPERATION_REMOVE PatchOperation = "remove"
	PATCHOPERATION_REPLACE PatchOperation = "replace"
	PATCHOPERATION_TEST PatchOperation = "test"
)
