/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SqnScheme string
// enum type
// List of SqnScheme 
const (
	SQNSCHEME_GENERAL SqnScheme = "GENERAL"
	SQNSCHEME_NON_TIME_BASED SqnScheme = "NON_TIME_BASED"
	SQNSCHEME_TIME_BASED SqnScheme = "TIME_BASED"
)
