/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type CoreNetworkType string
// enum type
// List of CoreNetworkType 
const (
	CORENETWORKTYPE__5_GC CoreNetworkType = "5GC"
	CORENETWORKTYPE_EPC CoreNetworkType = "EPC"
)
