/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LoggingDurationMdtAnyOf string

// List of LoggingDurationMdtAnyOf 
const (
	LOGGINGDURATIONMDTANYOF__600 LoggingDurationMdtAnyOf = "600"
	LOGGINGDURATIONMDTANYOF__1200 LoggingDurationMdtAnyOf = "1200"
	LOGGINGDURATIONMDTANYOF__2400 LoggingDurationMdtAnyOf = "2400"
	LOGGINGDURATIONMDTANYOF__3600 LoggingDurationMdtAnyOf = "3600"
	LOGGINGDURATIONMDTANYOF__5400 LoggingDurationMdtAnyOf = "5400"
	LOGGINGDURATIONMDTANYOF__7200 LoggingDurationMdtAnyOf = "7200"
)
