/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type GroupIdentifiers struct {


	
	// simple type
 
	

	ExtGroupId *string `json:"extGroupId,omitempty" yaml:"extGroupId" bson:"extGroupId" mapstructure:"ExtGroupId"`
 
	

	IntGroupId *string `json:"intGroupId,omitempty" yaml:"intGroupId" bson:"intGroupId" mapstructure:"IntGroupId"`
 
	

	UeIdList *[]UeId `json:"ueIdList,omitempty" yaml:"ueIdList" bson:"ueIdList" mapstructure:"UeIdList"`
}
