/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UeReachability string
// enum type
// List of UeReachability 
const (
	UEREACHABILITY_UNREACHABLE UeReachability = "UNREACHABLE"
	UEREACHABILITY_REACHABLE UeReachability = "REACHABLE"
	UEREACHABILITY_REGULATORY_ONLY UeReachability = "REGULATORY_ONLY"
)
