/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type RouteToLocation struct {


	
	// simple type
 
	

	Dnai string `json:"dnai" yaml:"dnai" bson:"dnai" mapstructure:"Dnai"`
 
	

	RouteInfo *RouteInformation `json:"routeInfo,omitempty" yaml:"routeInfo" bson:"routeInfo" mapstructure:"RouteInfo"`
 
	

	RouteProfId *string `json:"routeProfId,omitempty" yaml:"routeProfId" bson:"routeProfId" mapstructure:"RouteProfId"`
}
