/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EpsIwkPgw struct {


	
	// simple type
 
	

	PgwFqdn string `json:"pgwFqdn" yaml:"pgwFqdn" bson:"pgwFqdn" mapstructure:"PgwFqdn"`
 
	

	SmfInstanceId string `json:"smfInstanceId" yaml:"smfInstanceId" bson:"smfInstanceId" mapstructure:"SmfInstanceId"`
}
