/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type Model5GvnGroupConfiguration struct {


	
	// simple type
 
	

	Var5gVnGroupData *Model5GvnGroupData `json:"5gVnGroupData,omitempty" yaml:"5gVnGroupData" bson:"5gVnGroupData" mapstructure:"Var5gVnGroupData"`
 
	

	Members *[]string `json:"members,omitempty" yaml:"members" bson:"members" mapstructure:"Members"`
 
	

	ReferenceId *int32 `json:"referenceId,omitempty" yaml:"referenceId" bson:"referenceId" mapstructure:"ReferenceId"`
 
	

	AfInstanceId *string `json:"afInstanceId,omitempty" yaml:"afInstanceId" bson:"afInstanceId" mapstructure:"AfInstanceId"`
 
	

	InternalGroupIdentifier *string `json:"internalGroupIdentifier,omitempty" yaml:"internalGroupIdentifier" bson:"internalGroupIdentifier" mapstructure:"InternalGroupIdentifier"`
 
	

	MtcProviderInformation *string `json:"mtcProviderInformation,omitempty" yaml:"mtcProviderInformation" bson:"mtcProviderInformation" mapstructure:"MtcProviderInformation"`
}
