/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// SmfSubscriptionInfo - Information related to active subscriptions at the SMF(s)
type SmfSubscriptionInfo struct {


	
	// simple type
 
	

	SmfSubscriptionList []SmfSubscriptionItem `json:"smfSubscriptionList" yaml:"smfSubscriptionList" bson:"smfSubscriptionList" mapstructure:"SmfSubscriptionList"`
}
