/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// ApplicationDataChangeNotif - Contains changed application data for which notification was requested.
type ApplicationDataChangeNotif struct {


	
	// simple type
 
	

	IptvConfigData *IptvConfigData `json:"iptvConfigData,omitempty" yaml:"iptvConfigData" bson:"iptvConfigData" mapstructure:"IptvConfigData"`
 
	

	PfdData *PfdChangeNotification `json:"pfdData,omitempty" yaml:"pfdData" bson:"pfdData" mapstructure:"PfdData"`
 
	

	BdtPolicyData *BdtPolicyData `json:"bdtPolicyData,omitempty" yaml:"bdtPolicyData" bson:"bdtPolicyData" mapstructure:"BdtPolicyData"`
 
	

	ResUri string `json:"resUri" yaml:"resUri" bson:"resUri" mapstructure:"ResUri"`
 
	

	SerParamData *ServiceParameterData `json:"serParamData,omitempty" yaml:"serParamData" bson:"serParamData" mapstructure:"SerParamData"`
}
