/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// BdtData - Contains the background data transfer data.
type BdtData struct {


	
	// simple type
 
	

	AspId string `json:"aspId" yaml:"aspId" bson:"aspId" mapstructure:"AspId"`
 
	

	TransPolicy TransferPolicy `json:"transPolicy" yaml:"transPolicy" bson:"transPolicy" mapstructure:"TransPolicy"`

	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154. 
	

	BdtRefId *string `json:"bdtRefId,omitempty" yaml:"bdtRefId" bson:"bdtRefId" mapstructure:"BdtRefId"`
 
	

	NwAreaInfo *NetworkAreaInfo `json:"nwAreaInfo,omitempty" yaml:"nwAreaInfo" bson:"nwAreaInfo" mapstructure:"NwAreaInfo"`
 
	

	NumOfUes *int32 `json:"numOfUes,omitempty" yaml:"numOfUes" bson:"numOfUes" mapstructure:"NumOfUes"`
 
	

	VolPerUe *UsageThreshold `json:"volPerUe,omitempty" yaml:"volPerUe" bson:"volPerUe" mapstructure:"VolPerUe"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	Snssai *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai" mapstructure:"Snssai"`

	// Identify a traffic descriptor as defined in Figure 5.2.2 of 3GPP TS 24.526, octets v+5 to w. 
	

	TrafficDes *string `json:"trafficDes,omitempty" yaml:"trafficDes" bson:"trafficDes" mapstructure:"TrafficDes"`
 
	

	BdtpStatus *BdtPolicyStatus `json:"bdtpStatus,omitempty" yaml:"bdtpStatus" bson:"bdtpStatus" mapstructure:"BdtpStatus"`
 
	

	SuppFeat *string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat" mapstructure:"SuppFeat"`
}
