/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LoggingIntervalNrMdtAnyOf string

// List of LoggingIntervalNrMdtAnyOf 
const (
	LOGGINGINTERVALNRMDTANYOF__128 LoggingIntervalNrMdtAnyOf = "128"
	LOGGINGINTERVALNRMDTANYOF__256 LoggingIntervalNrMdtAnyOf = "256"
	LOGGINGINTERVALNRMDTANYOF__512 LoggingIntervalNrMdtAnyOf = "512"
	LOGGINGINTERVALNRMDTANYOF__1024 LoggingIntervalNrMdtAnyOf = "1024"
	LOGGINGINTERVALNRMDTANYOF__2048 LoggingIntervalNrMdtAnyOf = "2048"
	LOGGINGINTERVALNRMDTANYOF__3072 LoggingIntervalNrMdtAnyOf = "3072"
	LOGGINGINTERVALNRMDTANYOF__4096 LoggingIntervalNrMdtAnyOf = "4096"
	LOGGINGINTERVALNRMDTANYOF__6144 LoggingIntervalNrMdtAnyOf = "6144"
	LOGGINGINTERVALNRMDTANYOF__320 LoggingIntervalNrMdtAnyOf = "320"
	LOGGINGINTERVALNRMDTANYOF__640 LoggingIntervalNrMdtAnyOf = "640"
	LOGGINGINTERVALNRMDTANYOF_INFINITY LoggingIntervalNrMdtAnyOf = "infinity"
)
