/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EeGroupProfileData struct {


	
	// simple type
 
	

	RestrictedEventTypes *[]EventType `json:"restrictedEventTypes,omitempty" yaml:"restrictedEventTypes" bson:"restrictedEventTypes" mapstructure:"RestrictedEventTypes"`

	// A map (list of key-value pairs where EventType serves as key) of MTC provider lists. In addition to defined EventTypes, the key value \"ALL\" may be used to identify a map entry which contains a list of MtcProviders that are allowed monitoring all Event Types. 
	

	AllowedMtcProvider *map[string][]MtcProvider `json:"allowedMtcProvider,omitempty" yaml:"allowedMtcProvider" bson:"allowedMtcProvider" mapstructure:"AllowedMtcProvider"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
}
