/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type RmInfo struct {


	
	// simple type
 
	

	RmState RmState `json:"rmState" yaml:"rmState" bson:"rmState" mapstructure:"RmState"`
 
	

	AccessType AccessType `json:"accessType" yaml:"accessType" bson:"accessType" mapstructure:"AccessType"`
}
