/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CodeWordIndAnyOf string

// List of CodeWordIndAnyOf 
const (
	CODEWORDINDANYOF_UE CodeWordIndAnyOf = "CODEWORD_CHECK_IN_UE"
	CODEWORDINDANYOF_GMLC CodeWordIndAnyOf = "CODEWORD_CHECK_IN_GMLC"
)
