/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ImsVoPs string
// enum type
// List of ImsVoPs 
const (
	IMSVOPS_HOMOGENEOUS_SUPPORT ImsVoPs = "HOMOGENEOUS_SUPPORT"
	IMSVOPS_HOMOGENEOUS_NON_SUPPORT ImsVoPs = "HOMOGENEOUS_NON_SUPPORT"
	IMSVOPS_NON_HOMOGENEOUS_OR_UNKNOWN ImsVoPs = "NON_HOMOGENEOUS_OR_UNKNOWN"
)
