/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type NotifyItem struct {


	
	// simple type
 
	

	ResourceId string `json:"resourceId" yaml:"resourceId" bson:"resourceId" mapstructure:"ResourceId"`
 
	

	Changes []ChangeItem `json:"changes" yaml:"changes" bson:"changes" mapstructure:"Changes"`
}
