/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type IpSmGwRegistration struct {


	
	// simple type
 
	

	IpSmGwMapAddress *string `json:"ipSmGwMapAddress,omitempty" yaml:"ipSmGwMapAddress" bson:"ipSmGwMapAddress" mapstructure:"IpSmGwMapAddress"`
 
	

	IpSmGwDiameterAddress *NetworkNodeDiameterAddress `json:"ipSmGwDiameterAddress,omitempty" yaml:"ipSmGwDiameterAddress" bson:"ipSmGwDiameterAddress" mapstructure:"IpSmGwDiameterAddress"`
 
	

	UnriIndicator *bool `json:"unriIndicator,omitempty" yaml:"unriIndicator" bson:"unriIndicator" mapstructure:"UnriIndicator"`
}
