/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EventReportMode string
// enum type
// List of EventReportMode 
const (
	EVENTREPORTMODE_PERIODIC EventReportMode = "PERIODIC"
	EVENTREPORTMODE_ON_EVENT_DETECTION EventReportMode = "ON_EVENT_DETECTION"
)
