/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type MeasurementNrForMdt string
// enum type
// List of MeasurementNrForMdt 
const (
	MEASUREMENTNRFORMDT_M1 MeasurementNrForMdt = "M1"
	MEASUREMENTNRFORMDT_M2 MeasurementNrForMdt = "M2"
	MEASUREMENTNRFORMDT_M3 MeasurementNrForMdt = "M3"
	MEASUREMENTNRFORMDT_M4_DL MeasurementNrForMdt = "M4_DL"
	MEASUREMENTNRFORMDT_M4_UL MeasurementNrForMdt = "M4_UL"
	MEASUREMENTNRFORMDT_M5_DL MeasurementNrForMdt = "M5_DL"
	MEASUREMENTNRFORMDT_M5_UL MeasurementNrForMdt = "M5_UL"
	MEASUREMENTNRFORMDT_M6_DL MeasurementNrForMdt = "M6_DL"
	MEASUREMENTNRFORMDT_M6_UL MeasurementNrForMdt = "M6_UL"
	MEASUREMENTNRFORMDT_M7_DL MeasurementNrForMdt = "M7_DL"
	MEASUREMENTNRFORMDT_M7_UL MeasurementNrForMdt = "M7_UL"
	MEASUREMENTNRFORMDT_M8 MeasurementNrForMdt = "M8"
	MEASUREMENTNRFORMDT_M9 MeasurementNrForMdt = "M9"
)
