/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SequenceNumber struct {


	
	// simple type
 
	

	SqnScheme *SqnScheme `json:"sqnScheme,omitempty" yaml:"sqnScheme" bson:"sqnScheme" mapstructure:"SqnScheme"`
 
	

	Sqn *string `json:"sqn,omitempty" yaml:"sqn" bson:"sqn" mapstructure:"Sqn"`
 
	

	LastIndexes *map[string]int32 `json:"lastIndexes,omitempty" yaml:"lastIndexes" bson:"lastIndexes" mapstructure:"LastIndexes"`
 
	

	IndLength *int32 `json:"indLength,omitempty" yaml:"indLength" bson:"indLength" mapstructure:"IndLength"`
 
	

	DifSign *Sign `json:"difSign,omitempty" yaml:"difSign" bson:"difSign" mapstructure:"DifSign"`
}
