/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ScheduledCommunicationTime1 struct {


	
	// simple type

	// Identifies the day(s) of the week. If absent, it indicates every day of the week. 
	

	DaysOfWeek *[]int32 `json:"daysOfWeek,omitempty" yaml:"daysOfWeek" bson:"daysOfWeek" mapstructure:"DaysOfWeek"`

	// String with format partial-time or full-time as defined in clause 5.6 of IETF RFC 3339. Examples, 20:15:00, 20:15:00-08:00 (for 8 hours behind UTC). 
	

	TimeOfDayStart *string `json:"timeOfDayStart,omitempty" yaml:"timeOfDayStart" bson:"timeOfDayStart" mapstructure:"TimeOfDayStart"`

	// String with format partial-time or full-time as defined in clause 5.6 of IETF RFC 3339. Examples, 20:15:00, 20:15:00-08:00 (for 8 hours behind UTC). 
	

	TimeOfDayEnd *string `json:"timeOfDayEnd,omitempty" yaml:"timeOfDayEnd" bson:"timeOfDayEnd" mapstructure:"TimeOfDayEnd"`
}
