/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type MeasurementPeriodLteMdt string
// enum type
// List of MeasurementPeriodLteMdt 
const (
	MEASUREMENTPERIODLTEMDT__1024 MeasurementPeriodLteMdt = "1024"
	MEASUREMENTPERIODLTEMDT__1280 MeasurementPeriodLteMdt = "1280"
	MEASUREMENTPERIODLTEMDT__2048 MeasurementPeriodLteMdt = "2048"
	MEASUREMENTPERIODLTEMDT__2560 MeasurementPeriodLteMdt = "2560"
	MEASUREMENTPERIODLTEMDT__5120 MeasurementPeriodLteMdt = "5120"
	MEASUREMENTPERIODLTEMDT__10240 MeasurementPeriodLteMdt = "10240"
	MEASUREMENTPERIODLTEMDT__60000 MeasurementPeriodLteMdt = "60000"
)
