/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SensorMeasurementAnyOf string

// List of SensorMeasurementAnyOf 
const (
	SENSORMEASUREMENTANYOF_BAROMETRIC_PRESSURE SensorMeasurementAnyOf = "BAROMETRIC_PRESSURE"
	SENSORMEASUREMENTANYOF_UE_SPEED SensorMeasurementAnyOf = "UE_SPEED"
	SENSORMEASUREMENTANYOF_UE_ORIENTATION SensorMeasurementAnyOf = "UE_ORIENTATION"
)
