/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PduSessionContinuityIndAnyOf string

// List of PduSessionContinuityIndAnyOf 
const (
	PDUSESSIONCONTINUITYINDANYOF_MAINTAIN_PDUSESSION PduSessionContinuityIndAnyOf = "MAINTAIN_PDUSESSION"
	PDUSESSIONCONTINUITYINDANYOF_RECONNECT_PDUSESSION PduSessionContinuityIndAnyOf = "RECONNECT_PDUSESSION"
	PDUSESSIONCONTINUITYINDANYOF_RELEASE_PDUSESSION PduSessionContinuityIndAnyOf = "RELEASE_PDUSESSION"
)
