/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AppDescriptor struct {


	
	// simple type
 
	

	OsId *string `json:"osId,omitempty" yaml:"osId" bson:"osId" mapstructure:"OsId"`
 
	

	AppId *string `json:"appId,omitempty" yaml:"appId" bson:"appId" mapstructure:"AppId"`
}
