/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PduSessionTypeAnyOf string

// List of PduSessionTypeAnyOf 
const (
	PDUSESSIONTYPEANYOF_IPV4 PduSessionTypeAnyOf = "IPV4"
	PDUSESSIONTYPEANYOF_IPV6 PduSessionTypeAnyOf = "IPV6"
	PDUSESSIONTYPEANYOF_IPV4_V6 PduSessionTypeAnyOf = "IPV4V6"
	PDUSESSIONTYPEANYOF_UNSTRUCTURED PduSessionTypeAnyOf = "UNSTRUCTURED"
	PDUSESSIONTYPEANYOF_ETHERNET PduSessionTypeAnyOf = "ETHERNET"
)
