/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type PpMaximumResponseTime struct {


	
	// simple type
 
	

	MaximumResponseTime int32 `json:"maximumResponseTime" yaml:"maximumResponseTime" bson:"maximumResponseTime" mapstructure:"MaximumResponseTime"`
 
	

	AfInstanceId string `json:"afInstanceId" yaml:"afInstanceId" bson:"afInstanceId" mapstructure:"AfInstanceId"`
 
	

	ReferenceId int32 `json:"referenceId" yaml:"referenceId" bson:"referenceId" mapstructure:"ReferenceId"`
 
	

	ValidityTime *time.Time `json:"validityTime,omitempty" yaml:"validityTime" bson:"validityTime" mapstructure:"ValidityTime"`
 
	

	MtcProviderInformation *string `json:"mtcProviderInformation,omitempty" yaml:"mtcProviderInformation" bson:"mtcProviderInformation" mapstructure:"MtcProviderInformation"`
}
