/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SmsSupport string
// enum type
// List of SmsSupport 
const (
	SMSSUPPORT__3_GPP SmsSupport = "3GPP"
	SMSSUPPORT_NON_3_GPP SmsSupport = "NON_3GPP"
	SMSSUPPORT_BOTH SmsSupport = "BOTH"
	SMSSUPPORT_NONE SmsSupport = "NONE"
)
