/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type TrafficInfluDataNotif struct {


	
	// simple type
 
	

	ResUri string `json:"resUri" yaml:"resUri" bson:"resUri" mapstructure:"ResUri"`
 
	

	TrafficInfluData *TrafficInfluData `json:"trafficInfluData,omitempty" yaml:"trafficInfluData" bson:"trafficInfluData" mapstructure:"TrafficInfluData"`
}
