/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UncertaintyEllipse struct {


	
	// simple type
 
	

	SemiMajor float32 `json:"semiMajor" yaml:"semiMajor" bson:"semiMajor" mapstructure:"SemiMajor"`
 
	

	SemiMinor float32 `json:"semiMinor" yaml:"semiMinor" bson:"semiMinor" mapstructure:"SemiMinor"`
 
	

	OrientationMajor int32 `json:"orientationMajor" yaml:"orientationMajor" bson:"orientationMajor" mapstructure:"OrientationMajor"`
}
