/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SessionManagementSubscriptionData struct {


	
	// simple type
 
	

	SingleNssai Snssai `json:"singleNssai" yaml:"singleNssai" bson:"singleNssai" mapstructure:"SingleNssai"`

	// A map (list of key-value pairs where Dnn, or optionally the Wildcard DNN, serves as key) of DnnConfigurations 
	

	DnnConfigurations *map[string]DnnConfiguration `json:"dnnConfigurations,omitempty" yaml:"dnnConfigurations" bson:"dnnConfigurations" mapstructure:"DnnConfigurations"`
 
	

	InternalGroupIds *[]string `json:"internalGroupIds,omitempty" yaml:"internalGroupIds" bson:"internalGroupIds" mapstructure:"InternalGroupIds"`
 
	

	SharedVnGroupDataIds *map[string]string `json:"sharedVnGroupDataIds,omitempty" yaml:"sharedVnGroupDataIds" bson:"sharedVnGroupDataIds" mapstructure:"SharedVnGroupDataIds"`
 
	

	SharedDnnConfigurationsId *string `json:"sharedDnnConfigurationsId,omitempty" yaml:"sharedDnnConfigurationsId" bson:"sharedDnnConfigurationsId" mapstructure:"SharedDnnConfigurationsId"`
 
	

	OdbPacketServices *OdbPacketServices `json:"odbPacketServices,omitempty" yaml:"odbPacketServices" bson:"odbPacketServices" mapstructure:"OdbPacketServices"`
 
	

	TraceData *TraceData `json:"traceData,omitempty" yaml:"traceData" bson:"traceData" mapstructure:"TraceData"`
 
	

	SharedTraceDataId *string `json:"sharedTraceDataId,omitempty" yaml:"sharedTraceDataId" bson:"sharedTraceDataId" mapstructure:"SharedTraceDataId"`
 
	

	ExpectedUeBehavioursList *map[string]ExpectedUeBehaviourData `json:"expectedUeBehavioursList,omitempty" yaml:"expectedUeBehavioursList" bson:"expectedUeBehavioursList" mapstructure:"ExpectedUeBehavioursList"`
 
	

	SuggestedPacketNumDlList *map[string]SuggestedPacketNumDl `json:"suggestedPacketNumDlList,omitempty" yaml:"suggestedPacketNumDlList" bson:"suggestedPacketNumDlList" mapstructure:"SuggestedPacketNumDlList"`
 
	

	Var3gppChargingCharacteristics *string `json:"3gppChargingCharacteristics,omitempty" yaml:"3gppChargingCharacteristics" bson:"3gppChargingCharacteristics" mapstructure:"Var3gppChargingCharacteristics"`
}
