/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LoggingDurationMdt string
// enum type
// List of LoggingDurationMdt 
const (
	LOGGINGDURATIONMDT__600 LoggingDurationMdt = "600"
	LOGGINGDURATIONMDT__1200 LoggingDurationMdt = "1200"
	LOGGINGDURATIONMDT__2400 LoggingDurationMdt = "2400"
	LOGGINGDURATIONMDT__3600 LoggingDurationMdt = "3600"
	LOGGINGDURATIONMDT__5400 LoggingDurationMdt = "5400"
	LOGGINGDURATIONMDT__7200 LoggingDurationMdt = "7200"
)
