/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


// TemporalValidity - Indicates the time interval(s) during which the AF request is to be applied
type TemporalValidity struct {


	
	// simple type
 
	

	StartTime *time.Time `json:"startTime,omitempty" yaml:"startTime" bson:"startTime" mapstructure:"StartTime"`
 
	

	StopTime *time.Time `json:"stopTime,omitempty" yaml:"stopTime" bson:"stopTime" mapstructure:"StopTime"`
}
