/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type TraceDepthAnyOf string

// List of TraceDepthAnyOf 
const (
	TRACEDEPTHANYOF_MINIMUM TraceDepthAnyOf = "MINIMUM"
	TRACEDEPTHANYOF_MEDIUM TraceDepthAnyOf = "MEDIUM"
	TRACEDEPTHANYOF_MAXIMUM TraceDepthAnyOf = "MAXIMUM"
	TRACEDEPTHANYOF_MINIMUM_WO_VENDOR_EXTENSION TraceDepthAnyOf = "MINIMUM_WO_VENDOR_EXTENSION"
	TRACEDEPTHANYOF_MEDIUM_WO_VENDOR_EXTENSION TraceDepthAnyOf = "MEDIUM_WO_VENDOR_EXTENSION"
	TRACEDEPTHANYOF_MAXIMUM_WO_VENDOR_EXTENSION TraceDepthAnyOf = "MAXIMUM_WO_VENDOR_EXTENSION"
)
