/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EllipsoidArcAllOf struct {


	
	// simple type
 
	

	Point GeographicalCoordinates `json:"point" yaml:"point" bson:"point" mapstructure:"Point"`
 
	

	InnerRadius int32 `json:"innerRadius" yaml:"innerRadius" bson:"innerRadius" mapstructure:"InnerRadius"`
 
	

	UncertaintyRadius float32 `json:"uncertaintyRadius" yaml:"uncertaintyRadius" bson:"uncertaintyRadius" mapstructure:"UncertaintyRadius"`
 
	

	OffsetAngle int32 `json:"offsetAngle" yaml:"offsetAngle" bson:"offsetAngle" mapstructure:"OffsetAngle"`
 
	

	IncludedAngle int32 `json:"includedAngle" yaml:"includedAngle" bson:"includedAngle" mapstructure:"IncludedAngle"`
 
	

	Confidence int32 `json:"confidence" yaml:"confidence" bson:"confidence" mapstructure:"Confidence"`
}
