/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type SmsfRegistration struct {


	
	// simple type
 
	

	SmsfInstanceId string `json:"smsfInstanceId" yaml:"smsfInstanceId" bson:"smsfInstanceId" mapstructure:"SmsfInstanceId"`
 
	

	SmsfSetId *string `json:"smsfSetId,omitempty" yaml:"smsfSetId" bson:"smsfSetId" mapstructure:"SmsfSetId"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
 
	

	PlmnId PlmnId `json:"plmnId" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	SmsfMAPAddress *string `json:"smsfMAPAddress,omitempty" yaml:"smsfMAPAddress" bson:"smsfMAPAddress" mapstructure:"SmsfMAPAddress"`
 
	

	SmsfDiameterAddress *NetworkNodeDiameterAddress `json:"smsfDiameterAddress,omitempty" yaml:"smsfDiameterAddress" bson:"smsfDiameterAddress" mapstructure:"SmsfDiameterAddress"`
 
	

	RegistrationTime *time.Time `json:"registrationTime,omitempty" yaml:"registrationTime" bson:"registrationTime" mapstructure:"RegistrationTime"`
 
	

	ContextInfo *ContextInfo `json:"contextInfo,omitempty" yaml:"contextInfo" bson:"contextInfo" mapstructure:"ContextInfo"`
}
