/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ReportIntervalNrMdt string
// enum type
// List of ReportIntervalNrMdt 
const (
	REPORTINTERVALNRMDT__120 ReportIntervalNrMdt = "120"
	REPORTINTERVALNRMDT__240 ReportIntervalNrMdt = "240"
	REPORTINTERVALNRMDT__480 ReportIntervalNrMdt = "480"
	REPORTINTERVALNRMDT__640 ReportIntervalNrMdt = "640"
	REPORTINTERVALNRMDT__1024 ReportIntervalNrMdt = "1024"
	REPORTINTERVALNRMDT__2048 ReportIntervalNrMdt = "2048"
	REPORTINTERVALNRMDT__5120 ReportIntervalNrMdt = "5120"
	REPORTINTERVALNRMDT__10240 ReportIntervalNrMdt = "10240"
	REPORTINTERVALNRMDT__20480 ReportIntervalNrMdt = "20480"
	REPORTINTERVALNRMDT__40960 ReportIntervalNrMdt = "40960"
	REPORTINTERVALNRMDT__60000 ReportIntervalNrMdt = "60000"
	REPORTINTERVALNRMDT__360000 ReportIntervalNrMdt = "360000"
	REPORTINTERVALNRMDT__720000 ReportIntervalNrMdt = "720000"
	REPORTINTERVALNRMDT__1800000 ReportIntervalNrMdt = "1800000"
	REPORTINTERVALNRMDT__3600000 ReportIntervalNrMdt = "3600000"
)
