/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LcsPrivacyData struct {


	
	// simple type
 
	

	Lpi *Lpi `json:"lpi,omitempty" yaml:"lpi" bson:"lpi" mapstructure:"Lpi"`
 
	

	UnrelatedClass *UnrelatedClass `json:"unrelatedClass,omitempty" yaml:"unrelatedClass" bson:"unrelatedClass" mapstructure:"UnrelatedClass"`
 
	

	PlmnOperatorClasses *[]PlmnOperatorClass `json:"plmnOperatorClasses,omitempty" yaml:"plmnOperatorClasses" bson:"plmnOperatorClasses" mapstructure:"PlmnOperatorClasses"`
}
