/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UeContextInSmfData struct {


	
	// simple type

	// A map (list of key-value pairs where PduSessionId serves as key) of PduSessions 
	

	PduSessions *map[string]PduSession `json:"pduSessions,omitempty" yaml:"pduSessions" bson:"pduSessions" mapstructure:"PduSessions"`
 
	

	PgwInfo *[]PgwInfo `json:"pgwInfo,omitempty" yaml:"pgwInfo" bson:"pgwInfo" mapstructure:"PgwInfo"`
 
	

	EmergencyInfo *EmergencyInfo `json:"emergencyInfo,omitempty" yaml:"emergencyInfo" bson:"emergencyInfo" mapstructure:"EmergencyInfo"`
}
