/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PrivacyCheckRelatedAction string
// enum type
// List of PrivacyCheckRelatedAction 
const (
	PRIVACYCHECKRELATEDACTION_NOT_ALLOWED PrivacyCheckRelatedAction = "LOCATION_NOT_ALLOWED"
	PRIVACYCHECKRELATEDACTION_ALLOWED_WITH_NOTIFICATION PrivacyCheckRelatedAction = "LOCATION_ALLOWED_WITH_NOTIFICATION"
	PRIVACYCHECKRELATEDACTION_ALLOWED_WITHOUT_NOTIFICATION PrivacyCheckRelatedAction = "LOCATION_ALLOWED_WITHOUT_NOTIFICATION"
	PRIVACYCHECKRELATEDACTION_ALLOWED_WITHOUT_RESPONSE PrivacyCheckRelatedAction = "LOCATION_ALLOWED_WITHOUT_RESPONSE"
	PRIVACYCHECKRELATEDACTION_RESTRICTED_WITHOUT_RESPONSE PrivacyCheckRelatedAction = "LOCATION_RESTRICTED_WITHOUT_RESPONSE"
)
