/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// PolicyDataChangeNotification - Contains changed policy data for which notification was requested.
type PolicyDataChangeNotification struct {


	
	// simple type
 
	

	AmPolicyData *AmPolicyData `json:"amPolicyData,omitempty" yaml:"amPolicyData" bson:"amPolicyData" mapstructure:"AmPolicyData"`
 
	

	UePolicySet *UePolicySet `json:"uePolicySet,omitempty" yaml:"uePolicySet" bson:"uePolicySet" mapstructure:"UePolicySet"`
 
	

	PlmnUePolicySet *UePolicySet `json:"plmnUePolicySet,omitempty" yaml:"plmnUePolicySet" bson:"plmnUePolicySet" mapstructure:"PlmnUePolicySet"`
 
	

	SmPolicyData *SmPolicyData `json:"smPolicyData,omitempty" yaml:"smPolicyData" bson:"smPolicyData" mapstructure:"SmPolicyData"`
 
	

	UsageMonData *UsageMonData `json:"usageMonData,omitempty" yaml:"usageMonData" bson:"usageMonData" mapstructure:"UsageMonData"`
 
	

	SponsorConnectivityData *SponsorConnectivityData `json:"SponsorConnectivityData,omitempty" yaml:"SponsorConnectivityData" bson:"SponsorConnectivityData" mapstructure:"SponsorConnectivityData"`
 
	

	BdtData *BdtData `json:"bdtData,omitempty" yaml:"bdtData" bson:"bdtData" mapstructure:"BdtData"`
 
	

	OpSpecData *OperatorSpecificDataContainer `json:"opSpecData,omitempty" yaml:"opSpecData" bson:"opSpecData" mapstructure:"OpSpecData"`
 
	

	OpSpecDataMap *map[string]OperatorSpecificDataContainer `json:"opSpecDataMap,omitempty" yaml:"opSpecDataMap" bson:"opSpecDataMap" mapstructure:"OpSpecDataMap"`
 
	

	UeId *string `json:"ueId,omitempty" yaml:"ueId" bson:"ueId" mapstructure:"UeId"`
 
	

	SponsorId *string `json:"sponsorId,omitempty" yaml:"sponsorId" bson:"sponsorId" mapstructure:"SponsorId"`

	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154. 
	

	BdtRefId *string `json:"bdtRefId,omitempty" yaml:"bdtRefId" bson:"bdtRefId" mapstructure:"BdtRefId"`
 
	

	UsageMonId *string `json:"usageMonId,omitempty" yaml:"usageMonId" bson:"usageMonId" mapstructure:"UsageMonId"`
 
	

	PlmnId *PlmnId `json:"plmnId,omitempty" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	DelResources *[]string `json:"delResources,omitempty" yaml:"delResources" bson:"delResources" mapstructure:"DelResources"`
 
	

	NotifId *string `json:"notifId,omitempty" yaml:"notifId" bson:"notifId" mapstructure:"NotifId"`
 
	

	ReportedFragments *[]NotificationItem `json:"reportedFragments,omitempty" yaml:"reportedFragments" bson:"reportedFragments" mapstructure:"ReportedFragments"`
}
