/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CollectionPeriodRmmLteMdtAnyOf string

// List of CollectionPeriodRmmLteMdtAnyOf 
const (
	COLLECTIONPERIODRMMLTEMDTANYOF__1024 CollectionPeriodRmmLteMdtAnyOf = "1024"
	COLLECTIONPERIODRMMLTEMDTANYOF__1280 CollectionPeriodRmmLteMdtAnyOf = "1280"
	COLLECTIONPERIODRMMLTEMDTANYOF__2048 CollectionPeriodRmmLteMdtAnyOf = "2048"
	COLLECTIONPERIODRMMLTEMDTANYOF__2560 CollectionPeriodRmmLteMdtAnyOf = "2560"
	COLLECTIONPERIODRMMLTEMDTANYOF__5120 CollectionPeriodRmmLteMdtAnyOf = "5120"
	COLLECTIONPERIODRMMLTEMDTANYOF__10240 CollectionPeriodRmmLteMdtAnyOf = "10240"
	COLLECTIONPERIODRMMLTEMDTANYOF__60000 CollectionPeriodRmmLteMdtAnyOf = "60000"
)
