/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// BdtDataPatch - Contains the modified background data transfer data.
type BdtDataPatch struct {


	
	// simple type
 
	

	TransPolicy *TransferPolicy `json:"transPolicy,omitempty" yaml:"transPolicy" bson:"transPolicy" mapstructure:"TransPolicy"`
 
	

	BdtpStatus *BdtPolicyStatus `json:"bdtpStatus,omitempty" yaml:"bdtpStatus" bson:"bdtpStatus" mapstructure:"BdtpStatus"`
}
