/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EeSubscription struct {


	
	// simple type
 
	

	CallbackReference string `json:"callbackReference" yaml:"callbackReference" bson:"callbackReference" mapstructure:"CallbackReference"`

	// A map (list of key-value pairs where ReferenceId serves as key) of MonitoringConfigurations 
	

	MonitoringConfigurations map[string]MonitoringConfiguration `json:"monitoringConfigurations" yaml:"monitoringConfigurations" bson:"monitoringConfigurations" mapstructure:"MonitoringConfigurations"`
 
	

	ReportingOptions *ReportingOptions `json:"reportingOptions,omitempty" yaml:"reportingOptions" bson:"reportingOptions" mapstructure:"ReportingOptions"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
 
	

	SubscriptionId *string `json:"subscriptionId,omitempty" yaml:"subscriptionId" bson:"subscriptionId" mapstructure:"SubscriptionId"`
 
	

	ContextInfo *ContextInfo `json:"contextInfo,omitempty" yaml:"contextInfo" bson:"contextInfo" mapstructure:"ContextInfo"`
 
	

	EpcAppliedInd *bool `json:"epcAppliedInd,omitempty" yaml:"epcAppliedInd" bson:"epcAppliedInd" mapstructure:"EpcAppliedInd"`
 
	

	ScefDiamHost *string `json:"scefDiamHost,omitempty" yaml:"scefDiamHost" bson:"scefDiamHost" mapstructure:"ScefDiamHost"`
 
	

	ScefDiamRealm *string `json:"scefDiamRealm,omitempty" yaml:"scefDiamRealm" bson:"scefDiamRealm" mapstructure:"ScefDiamRealm"`
 
	

	NotifyCorrelationId *string `json:"notifyCorrelationId,omitempty" yaml:"notifyCorrelationId" bson:"notifyCorrelationId" mapstructure:"NotifyCorrelationId"`
}
