/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ContextDataSetNameAnyOf string

// List of ContextDataSetNameAnyOf 
const (
	CONTEXTDATASETNAMEANYOF_AMF_3_GPP ContextDataSetNameAnyOf = "AMF_3GPP"
	CONTEXTDATASETNAMEANYOF_AMF_NON_3_GPP ContextDataSetNameAnyOf = "AMF_NON_3GPP"
	CONTEXTDATASETNAMEANYOF_SDM_SUBSCRIPTIONS ContextDataSetNameAnyOf = "SDM_SUBSCRIPTIONS"
	CONTEXTDATASETNAMEANYOF_EE_SUBSCRIPTIONS ContextDataSetNameAnyOf = "EE_SUBSCRIPTIONS"
	CONTEXTDATASETNAMEANYOF_SMSF_3_GPP ContextDataSetNameAnyOf = "SMSF_3GPP"
	CONTEXTDATASETNAMEANYOF_SMSF_NON_3_GPP ContextDataSetNameAnyOf = "SMSF_NON_3GPP"
	CONTEXTDATASETNAMEANYOF_SUBS_TO_NOTIFY ContextDataSetNameAnyOf = "SUBS_TO_NOTIFY"
	CONTEXTDATASETNAMEANYOF_SMF_REG ContextDataSetNameAnyOf = "SMF_REG"
	CONTEXTDATASETNAMEANYOF_IP_SM_GW ContextDataSetNameAnyOf = "IP_SM_GW"
)
