/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type FrameRouteInfo struct {


	
	// simple type
 
	

	Ipv4Mask *string `json:"ipv4Mask,omitempty" yaml:"ipv4Mask" bson:"ipv4Mask" mapstructure:"Ipv4Mask"`
 
	

	Ipv6Prefix *Ipv6Prefix `json:"ipv6Prefix,omitempty" yaml:"ipv6Prefix" bson:"ipv6Prefix" mapstructure:"Ipv6Prefix"`
}
