/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type BdtPolicyData struct {


	
	// simple type
 
	

	InterGroupId *string `json:"interGroupId,omitempty" yaml:"interGroupId" bson:"interGroupId" mapstructure:"InterGroupId"`
 
	

	Supi *string `json:"supi,omitempty" yaml:"supi" bson:"supi" mapstructure:"Supi"`

	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154. 
	

	BdtRefId string `json:"bdtRefId" yaml:"bdtRefId" bson:"bdtRefId" mapstructure:"BdtRefId"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	Snssai *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai" mapstructure:"Snssai"`
 
	

	ResUri *string `json:"resUri,omitempty" yaml:"resUri" bson:"resUri" mapstructure:"ResUri"`
}
