/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PduSessionType string
// enum type
// List of PduSessionType 
const (
	PDUSESSIONTYPE_IPV4 PduSessionType = "IPV4"
	PDUSESSIONTYPE_IPV6 PduSessionType = "IPV6"
	PDUSESSIONTYPE_IPV4_V6 PduSessionType = "IPV4V6"
	PDUSESSIONTYPE_UNSTRUCTURED PduSessionType = "UNSTRUCTURED"
	PDUSESSIONTYPE_ETHERNET PduSessionType = "ETHERNET"
)
