/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AuthenticationSubscription struct {


	
	// simple type
 
	

	AuthenticationMethod AuthMethod `json:"authenticationMethod" yaml:"authenticationMethod" bson:"authenticationMethod" mapstructure:"AuthenticationMethod"`
 
	

	EncPermanentKey *string `json:"encPermanentKey,omitempty" yaml:"encPermanentKey" bson:"encPermanentKey" mapstructure:"EncPermanentKey"`
 
	

	ProtectionParameterId *string `json:"protectionParameterId,omitempty" yaml:"protectionParameterId" bson:"protectionParameterId" mapstructure:"ProtectionParameterId"`
 
	

	SequenceNumber *SequenceNumber `json:"sequenceNumber,omitempty" yaml:"sequenceNumber" bson:"sequenceNumber" mapstructure:"SequenceNumber"`
 
	

	AuthenticationManagementField *string `json:"authenticationManagementField,omitempty" yaml:"authenticationManagementField" bson:"authenticationManagementField" mapstructure:"AuthenticationManagementField"`
 
	

	AlgorithmId *string `json:"algorithmId,omitempty" yaml:"algorithmId" bson:"algorithmId" mapstructure:"AlgorithmId"`
 
	

	EncOpcKey *string `json:"encOpcKey,omitempty" yaml:"encOpcKey" bson:"encOpcKey" mapstructure:"EncOpcKey"`
 
	

	EncTopcKey *string `json:"encTopcKey,omitempty" yaml:"encTopcKey" bson:"encTopcKey" mapstructure:"EncTopcKey"`
 
	

	VectorGenerationInHss *bool `json:"vectorGenerationInHss,omitempty" yaml:"vectorGenerationInHss" bson:"vectorGenerationInHss" mapstructure:"VectorGenerationInHss"`
 
	

	N5gcAuthMethod *AuthMethod `json:"n5gcAuthMethod,omitempty" yaml:"n5gcAuthMethod" bson:"n5gcAuthMethod" mapstructure:"N5gcAuthMethod"`
 
	

	RgAuthenticationInd *bool `json:"rgAuthenticationInd,omitempty" yaml:"rgAuthenticationInd" bson:"rgAuthenticationInd" mapstructure:"RgAuthenticationInd"`
 
	

	Supi *string `json:"supi,omitempty" yaml:"supi" bson:"supi" mapstructure:"Supi"`
}
