/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AreaScope struct {


	
	// simple type
 
	

	EutraCellIdList *[]string `json:"eutraCellIdList,omitempty" yaml:"eutraCellIdList" bson:"eutraCellIdList" mapstructure:"EutraCellIdList"`
 
	

	NrCellIdList *[]string `json:"nrCellIdList,omitempty" yaml:"nrCellIdList" bson:"nrCellIdList" mapstructure:"NrCellIdList"`
 
	

	TacList *[]string `json:"tacList,omitempty" yaml:"tacList" bson:"tacList" mapstructure:"TacList"`
 
	

	TacInfoPerPlmn *map[string]TacInfo `json:"tacInfoPerPlmn,omitempty" yaml:"tacInfoPerPlmn" bson:"tacInfoPerPlmn" mapstructure:"TacInfoPerPlmn"`
}
