/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PrivacyCheckRelatedActionAnyOf string

// List of PrivacyCheckRelatedActionAnyOf 
const (
	PRIVACYCHECKRELATEDACTIONANYOF_NOT_ALLOWED PrivacyCheckRelatedActionAnyOf = "LOCATION_NOT_ALLOWED"
	PRIVACYCHECKRELATEDACTIONANYOF_ALLOWED_WITH_NOTIFICATION PrivacyCheckRelatedActionAnyOf = "LOCATION_ALLOWED_WITH_NOTIFICATION"
	PRIVACYCHECKRELATEDACTIONANYOF_ALLOWED_WITHOUT_NOTIFICATION PrivacyCheckRelatedActionAnyOf = "LOCATION_ALLOWED_WITHOUT_NOTIFICATION"
	PRIVACYCHECKRELATEDACTIONANYOF_ALLOWED_WITHOUT_RESPONSE PrivacyCheckRelatedActionAnyOf = "LOCATION_ALLOWED_WITHOUT_RESPONSE"
	PRIVACYCHECKRELATEDACTIONANYOF_RESTRICTED_WITHOUT_RESPONSE PrivacyCheckRelatedActionAnyOf = "LOCATION_RESTRICTED_WITHOUT_RESPONSE"
)
