/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// SmPolicyDataPatch - Contains the SM policy data for a given subscriber.
type SmPolicyDataPatch struct {


	
	// simple type
 
	

	UmData *map[string]UsageMonData `json:"umData,omitempty" yaml:"umData" bson:"umData" mapstructure:"UmData"`
 
	

	SmPolicySnssaiData *map[string]SmPolicySnssaiDataPatch `json:"smPolicySnssaiData,omitempty" yaml:"smPolicySnssaiData" bson:"smPolicySnssaiData" mapstructure:"SmPolicySnssaiData"`
}
