/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type OperatorSpecificDataContainer struct {


	
	// simple type
 
	

	DataType string `json:"dataType" yaml:"dataType" bson:"dataType" mapstructure:"DataType"`
 
	

	DataTypeDefinition *string `json:"dataTypeDefinition,omitempty" yaml:"dataTypeDefinition" bson:"dataTypeDefinition" mapstructure:"DataTypeDefinition"`
 
	

	Value string `json:"value" yaml:"value" bson:"value" mapstructure:"Value"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
}
