/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// SmPolicyDnnDataPatch - Contains the SM policy data for a given DNN (and S-NSSAI).
type SmPolicyDnnDataPatch struct {


	
	// simple type
 
	

	Dnn string `json:"dnn" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	BdtRefIds *map[string]string `json:"bdtRefIds,omitempty" yaml:"bdtRefIds" bson:"bdtRefIds" mapstructure:"BdtRefIds"`
}
