/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type RatType string
// enum type
// List of RatType 
const (
	RATTYPE_NR RatType = "NR"
	RATTYPE_EUTRA RatType = "EUTRA"
	RATTYPE_WLAN RatType = "WLAN"
	RATTYPE_VIRTUAL RatType = "VIRTUAL"
	RATTYPE_NBIOT RatType = "NBIOT"
	RATTYPE_WIRELINE RatType = "WIRELINE"
	RATTYPE_WIRELINE_CABLE RatType = "WIRELINE_CABLE"
	RATTYPE_WIRELINE_BBF RatType = "WIRELINE_BBF"
	RATTYPE_LTE_M RatType = "LTE-M"
	RATTYPE_NR_U RatType = "NR_U"
	RATTYPE_EUTRA_U RatType = "EUTRA_U"
	RATTYPE_TRUSTED_N3_GA RatType = "TRUSTED_N3GA"
	RATTYPE_TRUSTED_WLAN RatType = "TRUSTED_WLAN"
	RATTYPE_UTRA RatType = "UTRA"
	RATTYPE_GERA RatType = "GERA"
)
