/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type TrafficProfile string
// enum type
// List of TrafficProfile 
const (
	TRAFFICPROFILE_SINGLE_TRANS_UL TrafficProfile = "SINGLE_TRANS_UL"
	TRAFFICPROFILE_SINGLE_TRANS_DL TrafficProfile = "SINGLE_TRANS_DL"
	TRAFFICPROFILE_DUAL_TRANS_UL_FIRST TrafficProfile = "DUAL_TRANS_UL_FIRST"
	TRAFFICPROFILE_DUAL_TRANS_DL_FIRST TrafficProfile = "DUAL_TRANS_DL_FIRST"
	TRAFFICPROFILE_MULTI_TRANS TrafficProfile = "MULTI_TRANS"
)
