/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type IptvConfigData struct {


	
	// simple type
 
	

	Supi *string `json:"supi,omitempty" yaml:"supi" bson:"supi" mapstructure:"Supi"`
 
	

	InterGroupId *string `json:"interGroupId,omitempty" yaml:"interGroupId" bson:"interGroupId" mapstructure:"InterGroupId"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	Snssai *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai" mapstructure:"Snssai"`
 
	

	AfAppId string `json:"afAppId" yaml:"afAppId" bson:"afAppId" mapstructure:"AfAppId"`
 
	

	MultiAccCtrls map[string]MulticastAccessControl `json:"multiAccCtrls" yaml:"multiAccCtrls" bson:"multiAccCtrls" mapstructure:"MultiAccCtrls"`
 
	

	SuppFeat *string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat" mapstructure:"SuppFeat"`
 
	

	ResUri *string `json:"resUri,omitempty" yaml:"resUri" bson:"resUri" mapstructure:"ResUri"`
}
