/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type CivicAddress struct {


	
	// simple type
 
	

	Country *string `json:"country,omitempty" yaml:"country" bson:"country" mapstructure:"Country"`
 
	

	A1 *string `json:"A1,omitempty" yaml:"A1" bson:"A1" mapstructure:"A1"`
 
	

	A2 *string `json:"A2,omitempty" yaml:"A2" bson:"A2" mapstructure:"A2"`
 
	

	A3 *string `json:"A3,omitempty" yaml:"A3" bson:"A3" mapstructure:"A3"`
 
	

	A4 *string `json:"A4,omitempty" yaml:"A4" bson:"A4" mapstructure:"A4"`
 
	

	A5 *string `json:"A5,omitempty" yaml:"A5" bson:"A5" mapstructure:"A5"`
 
	

	A6 *string `json:"A6,omitempty" yaml:"A6" bson:"A6" mapstructure:"A6"`
 
	

	PRD *string `json:"PRD,omitempty" yaml:"PRD" bson:"PRD" mapstructure:"PRD"`
 
	

	POD *string `json:"POD,omitempty" yaml:"POD" bson:"POD" mapstructure:"POD"`
 
	

	STS *string `json:"STS,omitempty" yaml:"STS" bson:"STS" mapstructure:"STS"`
 
	

	HNO *string `json:"HNO,omitempty" yaml:"HNO" bson:"HNO" mapstructure:"HNO"`
 
	

	HNS *string `json:"HNS,omitempty" yaml:"HNS" bson:"HNS" mapstructure:"HNS"`
 
	

	LMK *string `json:"LMK,omitempty" yaml:"LMK" bson:"LMK" mapstructure:"LMK"`
 
	

	LOC *string `json:"LOC,omitempty" yaml:"LOC" bson:"LOC" mapstructure:"LOC"`
 
	

	NAM *string `json:"NAM,omitempty" yaml:"NAM" bson:"NAM" mapstructure:"NAM"`
 
	

	PC *string `json:"PC,omitempty" yaml:"PC" bson:"PC" mapstructure:"PC"`
 
	

	BLD *string `json:"BLD,omitempty" yaml:"BLD" bson:"BLD" mapstructure:"BLD"`
 
	

	UNIT *string `json:"UNIT,omitempty" yaml:"UNIT" bson:"UNIT" mapstructure:"UNIT"`
 
	

	FLR *string `json:"FLR,omitempty" yaml:"FLR" bson:"FLR" mapstructure:"FLR"`
 
	

	ROOM *string `json:"ROOM,omitempty" yaml:"ROOM" bson:"ROOM" mapstructure:"ROOM"`
 
	

	PLC *string `json:"PLC,omitempty" yaml:"PLC" bson:"PLC" mapstructure:"PLC"`
 
	

	PCN *string `json:"PCN,omitempty" yaml:"PCN" bson:"PCN" mapstructure:"PCN"`
 
	

	POBOX *string `json:"POBOX,omitempty" yaml:"POBOX" bson:"POBOX" mapstructure:"POBOX"`
 
	

	ADDCODE *string `json:"ADDCODE,omitempty" yaml:"ADDCODE" bson:"ADDCODE" mapstructure:"ADDCODE"`
 
	

	SEAT *string `json:"SEAT,omitempty" yaml:"SEAT" bson:"SEAT" mapstructure:"SEAT"`
 
	

	RD *string `json:"RD,omitempty" yaml:"RD" bson:"RD" mapstructure:"RD"`
 
	

	RDSEC *string `json:"RDSEC,omitempty" yaml:"RDSEC" bson:"RDSEC" mapstructure:"RDSEC"`
 
	

	RDBR *string `json:"RDBR,omitempty" yaml:"RDBR" bson:"RDBR" mapstructure:"RDBR"`
 
	

	RDSUBBR *string `json:"RDSUBBR,omitempty" yaml:"RDSUBBR" bson:"RDSUBBR" mapstructure:"RDSUBBR"`
 
	

	PRM *string `json:"PRM,omitempty" yaml:"PRM" bson:"PRM" mapstructure:"PRM"`
 
	

	POM *string `json:"POM,omitempty" yaml:"POM" bson:"POM" mapstructure:"POM"`
 
	

	UsageRules *string `json:"usageRules,omitempty" yaml:"usageRules" bson:"usageRules" mapstructure:"UsageRules"`
 
	

	Method *string `json:"method,omitempty" yaml:"method" bson:"method" mapstructure:"Method"`
 
	

	ProvidedBy *string `json:"providedBy,omitempty" yaml:"providedBy" bson:"providedBy" mapstructure:"ProvidedBy"`
}
