/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ReportAmountMdt string
// enum type
// List of ReportAmountMdt 
const (
	REPORTAMOUNTMDT__1 ReportAmountMdt = "1"
	REPORTAMOUNTMDT__2 ReportAmountMdt = "2"
	REPORTAMOUNTMDT__4 ReportAmountMdt = "4"
	REPORTAMOUNTMDT__8 ReportAmountMdt = "8"
	REPORTAMOUNTMDT__16 ReportAmountMdt = "16"
	REPORTAMOUNTMDT__32 ReportAmountMdt = "32"
	REPORTAMOUNTMDT__64 ReportAmountMdt = "64"
	REPORTAMOUNTMDT_INFINITY ReportAmountMdt = "infinity"
)
