/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UpConfidentiality string
// enum type
// List of UpConfidentiality 
const (
	UPCONFIDENTIALITY_REQUIRED UpConfidentiality = "REQUIRED"
	UPCONFIDENTIALITY_PREFERRED UpConfidentiality = "PREFERRED"
	UPCONFIDENTIALITY_NOT_NEEDED UpConfidentiality = "NOT_NEEDED"
)
