/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type IdentityData struct {


	
	// simple type
 
	

	SupiList *[]string `json:"supiList,omitempty" yaml:"supiList" bson:"supiList" mapstructure:"SupiList"`
 
	

	GpsiList *[]string `json:"gpsiList,omitempty" yaml:"gpsiList" bson:"gpsiList" mapstructure:"GpsiList"`
}
