/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type OperationMode string
// enum type
// List of OperationMode 
const (
	OPERATIONMODE_WB_S1 OperationMode = "WB_S1"
	OPERATIONMODE_NB_S1 OperationMode = "NB_S1"
	OPERATIONMODE_WB_N1 OperationMode = "WB_N1"
	OPERATIONMODE_NB_N1 OperationMode = "NB_N1"
)
