/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ReachabilityForSmsConfiguration string
// enum type
// List of ReachabilityForSmsConfiguration 
const (
	REACHABILITYFORSMSCONFIGURATION_NAS ReachabilityForSmsConfiguration = "REACHABILITY_FOR_SMS_OVER_NAS"
	REACHABILITYFORSMSCONFIGURATION_IP ReachabilityForSmsConfiguration = "REACHABILITY_FOR_SMS_OVER_IP"
)
