/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type WirelineArea struct {


	
	// simple type
 
	

	GlobalLineIds *[]string `json:"globalLineIds,omitempty" yaml:"globalLineIds" bson:"globalLineIds" mapstructure:"GlobalLineIds"`
 
	

	HfcNIds *[]string `json:"hfcNIds,omitempty" yaml:"hfcNIds" bson:"hfcNIds" mapstructure:"HfcNIds"`
 
	

	AreaCodeB *string `json:"areaCodeB,omitempty" yaml:"areaCodeB" bson:"areaCodeB" mapstructure:"AreaCodeB"`
 
	

	AreaCodeC *string `json:"areaCodeC,omitempty" yaml:"areaCodeC" bson:"areaCodeC" mapstructure:"AreaCodeC"`
}
