/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type ReportingOptions struct {


	
	// simple type
 
	

	ReportMode *EventReportMode `json:"reportMode,omitempty" yaml:"reportMode" bson:"reportMode" mapstructure:"ReportMode"`
 
	

	MaxNumOfReports *int32 `json:"maxNumOfReports,omitempty" yaml:"maxNumOfReports" bson:"maxNumOfReports" mapstructure:"MaxNumOfReports"`
 
	

	Expiry *time.Time `json:"expiry,omitempty" yaml:"expiry" bson:"expiry" mapstructure:"Expiry"`
 
	

	SamplingRatio *int32 `json:"samplingRatio,omitempty" yaml:"samplingRatio" bson:"samplingRatio" mapstructure:"SamplingRatio"`
 
	

	GuardTime *int32 `json:"guardTime,omitempty" yaml:"guardTime" bson:"guardTime" mapstructure:"GuardTime"`
 
	

	ReportPeriod *int32 `json:"reportPeriod,omitempty" yaml:"reportPeriod" bson:"reportPeriod" mapstructure:"ReportPeriod"`
}
