/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LocationAccuracy string
// enum type
// List of LocationAccuracy 
const (
	LOCATIONACCURACY_CELL_LEVEL LocationAccuracy = "CELL_LEVEL"
	LOCATIONACCURACY_TA_LEVEL LocationAccuracy = "TA_LEVEL"
	LOCATIONACCURACY_N3_IWF_LEVEL LocationAccuracy = "N3IWF_LEVEL"
	LOCATIONACCURACY_UE_IP LocationAccuracy = "UE_IP"
	LOCATIONACCURACY_UE_PORT LocationAccuracy = "UE_PORT"
)
