/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UeContextInSmsfData struct {


	
	// simple type
 
	

	SmsfInfo3GppAccess *SmsfInfo `json:"smsfInfo3GppAccess,omitempty" yaml:"smsfInfo3GppAccess" bson:"smsfInfo3GppAccess" mapstructure:"SmsfInfo3GppAccess"`
 
	

	SmsfInfoNon3GppAccess *SmsfInfo `json:"smsfInfoNon3GppAccess,omitempty" yaml:"smsfInfoNon3GppAccess" bson:"smsfInfoNon3GppAccess" mapstructure:"SmsfInfoNon3GppAccess"`
}
