/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// HssSubscriptionInfo - Information related to active subscriptions at the HSS(s)
type HssSubscriptionInfo struct {


	
	// simple type
 
	

	HssSubscriptionList []HssSubscriptionItem `json:"hssSubscriptionList" yaml:"hssSubscriptionList" bson:"hssSubscriptionList" mapstructure:"HssSubscriptionList"`
}
