/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LocationArea struct {


	
	// simple type

	// Identifies a list of geographic area of the user where the UE is located. 
	

	GeographicAreas *[]GeographicArea `json:"geographicAreas,omitempty" yaml:"geographicAreas" bson:"geographicAreas" mapstructure:"GeographicAreas"`

	// Identifies a list of civic addresses of the user where the UE is located. 
	

	CivicAddresses *[]CivicAddress `json:"civicAddresses,omitempty" yaml:"civicAddresses" bson:"civicAddresses" mapstructure:"CivicAddresses"`
 
	

	NwAreaInfo *NetworkAreaInfo `json:"nwAreaInfo,omitempty" yaml:"nwAreaInfo" bson:"nwAreaInfo" mapstructure:"NwAreaInfo"`
}
