/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UnrelatedClass struct {


	
	// simple type
 
	

	DefaultUnrelatedClass DefaultUnrelatedClass `json:"defaultUnrelatedClass" yaml:"defaultUnrelatedClass" bson:"defaultUnrelatedClass" mapstructure:"DefaultUnrelatedClass"`
 
	

	ExternalUnrelatedClass *ExternalUnrelatedClass `json:"externalUnrelatedClass,omitempty" yaml:"externalUnrelatedClass" bson:"externalUnrelatedClass" mapstructure:"ExternalUnrelatedClass"`
 
	

	ServiceTypeUnrelatedClasses *[]ServiceTypeUnrelatedClass `json:"serviceTypeUnrelatedClasses,omitempty" yaml:"serviceTypeUnrelatedClasses" bson:"serviceTypeUnrelatedClasses" mapstructure:"ServiceTypeUnrelatedClasses"`
}
