/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type CagData struct {


	
	// simple type

	// A map (list of key-value pairs where PlmnId serves as key) of CagInfo 
	

	CagInfos map[string]CagInfo `json:"cagInfos" yaml:"cagInfos" bson:"cagInfos" mapstructure:"CagInfos"`
 
	

	ProvisioningTime *time.Time `json:"provisioningTime,omitempty" yaml:"provisioningTime" bson:"provisioningTime" mapstructure:"ProvisioningTime"`
}
