/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OperationModeAnyOf string

// List of OperationModeAnyOf 
const (
	OPERATIONMODEANYOF_WB_S1 OperationModeAnyOf = "WB_S1"
	OPERATIONMODEANYOF_NB_S1 OperationModeAnyOf = "NB_S1"
	OPERATIONMODEANYOF_WB_N1 OperationModeAnyOf = "WB_N1"
	OPERATIONMODEANYOF_NB_N1 OperationModeAnyOf = "NB_N1"
)
