/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type MulticastAccessControl struct {


	
	// simple type
 
	

	SrcIpv4Addr *string `json:"srcIpv4Addr,omitempty" yaml:"srcIpv4Addr" bson:"srcIpv4Addr" mapstructure:"SrcIpv4Addr"`
 
	

	SrcIpv6Addr *Ipv6Addr `json:"srcIpv6Addr,omitempty" yaml:"srcIpv6Addr" bson:"srcIpv6Addr" mapstructure:"SrcIpv6Addr"`
 
	

	MulticastV4Addr *string `json:"multicastV4Addr,omitempty" yaml:"multicastV4Addr" bson:"multicastV4Addr" mapstructure:"MulticastV4Addr"`
 
	

	MulticastV6Addr *Ipv6Addr `json:"multicastV6Addr,omitempty" yaml:"multicastV6Addr" bson:"multicastV6Addr" mapstructure:"MulticastV6Addr"`
 
	

	AccStatus AccessRightStatus `json:"accStatus" yaml:"accStatus" bson:"accStatus" mapstructure:"AccStatus"`
}
