/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// NotificationItem - Identifies a data change notification when the change occurs in a fragment (subset of resource data) of a given resource.
type NotificationItem struct {


	
	// simple type
 
	

	ResourceId string `json:"resourceId" yaml:"resourceId" bson:"resourceId" mapstructure:"ResourceId"`
 
	

	NotifItems []UpdatedItem `json:"notifItems" yaml:"notifItems" bson:"notifItems" mapstructure:"NotifItems"`
}
