/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type RegistrationLocationInfo struct {


	
	// simple type
 
	

	AmfInstanceId string `json:"amfInstanceId" yaml:"amfInstanceId" bson:"amfInstanceId" mapstructure:"AmfInstanceId"`
 
	

	PlmnId *PlmnId `json:"plmnId,omitempty" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	VgmlcAddress *VgmlcAddress `json:"vgmlcAddress,omitempty" yaml:"vgmlcAddress" bson:"vgmlcAddress" mapstructure:"VgmlcAddress"`
 
	

	AccessTypeList []AccessType `json:"accessTypeList" yaml:"accessTypeList" bson:"accessTypeList" mapstructure:"AccessTypeList"`
}
