/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LcsMoServiceClass string
// enum type
// List of LcsMoServiceClass 
const (
	LCSMOSERVICECLASS_BASIC_SELF_LOCATION LcsMoServiceClass = "BASIC_SELF_LOCATION"
	LCSMOSERVICECLASS_AUTONOMOUS_SELF_LOCATION LcsMoServiceClass = "AUTONOMOUS_SELF_LOCATION"
	LCSMOSERVICECLASS_TRANSFER_TO_THIRD_PARTY LcsMoServiceClass = "TRANSFER_TO_THIRD_PARTY"
)
