/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AccessAndMobilitySubscriptionData struct {


	
	// simple type
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
 
	

	Gpsis *[]string `json:"gpsis,omitempty" yaml:"gpsis" bson:"gpsis" mapstructure:"Gpsis"`
 
	

	InternalGroupIds *[]string `json:"internalGroupIds,omitempty" yaml:"internalGroupIds" bson:"internalGroupIds" mapstructure:"InternalGroupIds"`
 
	

	SharedVnGroupDataIds *map[string]string `json:"sharedVnGroupDataIds,omitempty" yaml:"sharedVnGroupDataIds" bson:"sharedVnGroupDataIds" mapstructure:"SharedVnGroupDataIds"`
 
	

	SubscribedUeAmbr *Ambr `json:"subscribedUeAmbr,omitempty" yaml:"subscribedUeAmbr" bson:"subscribedUeAmbr" mapstructure:"SubscribedUeAmbr"`
 
	

	Nssai *Nssai `json:"nssai,omitempty" yaml:"nssai" bson:"nssai" mapstructure:"Nssai"`
 
	

	RatRestrictions *[]RatType `json:"ratRestrictions,omitempty" yaml:"ratRestrictions" bson:"ratRestrictions" mapstructure:"RatRestrictions"`
 
	

	ForbiddenAreas *[]Area `json:"forbiddenAreas,omitempty" yaml:"forbiddenAreas" bson:"forbiddenAreas" mapstructure:"ForbiddenAreas"`
 
	

	ServiceAreaRestriction *ServiceAreaRestriction `json:"serviceAreaRestriction,omitempty" yaml:"serviceAreaRestriction" bson:"serviceAreaRestriction" mapstructure:"ServiceAreaRestriction"`
 
	

	CoreNetworkTypeRestrictions *[]CoreNetworkType `json:"coreNetworkTypeRestrictions,omitempty" yaml:"coreNetworkTypeRestrictions" bson:"coreNetworkTypeRestrictions" mapstructure:"CoreNetworkTypeRestrictions"`
 
	

	RfspIndex *int32 `json:"rfspIndex,omitempty" yaml:"rfspIndex" bson:"rfspIndex" mapstructure:"RfspIndex"`
 
	

	SubsRegTimer *int32 `json:"subsRegTimer,omitempty" yaml:"subsRegTimer" bson:"subsRegTimer" mapstructure:"SubsRegTimer"`
 
	

	UeUsageType *int32 `json:"ueUsageType,omitempty" yaml:"ueUsageType" bson:"ueUsageType" mapstructure:"UeUsageType"`
 
	

	MpsPriority *bool `json:"mpsPriority,omitempty" yaml:"mpsPriority" bson:"mpsPriority" mapstructure:"MpsPriority"`
 
	

	McsPriority *bool `json:"mcsPriority,omitempty" yaml:"mcsPriority" bson:"mcsPriority" mapstructure:"McsPriority"`
 
	

	ActiveTime *int32 `json:"activeTime,omitempty" yaml:"activeTime" bson:"activeTime" mapstructure:"ActiveTime"`
 
	

	SorInfo *SorInfo `json:"sorInfo,omitempty" yaml:"sorInfo" bson:"sorInfo" mapstructure:"SorInfo"`
 
	

	SorInfoExpectInd *bool `json:"sorInfoExpectInd,omitempty" yaml:"sorInfoExpectInd" bson:"sorInfoExpectInd" mapstructure:"SorInfoExpectInd"`
 
	

	SorafRetrieval *bool `json:"sorafRetrieval,omitempty" yaml:"sorafRetrieval" bson:"sorafRetrieval" mapstructure:"SorafRetrieval"`
 
	

	SorUpdateIndicatorList *[]SorUpdateIndicator `json:"sorUpdateIndicatorList,omitempty" yaml:"sorUpdateIndicatorList" bson:"sorUpdateIndicatorList" mapstructure:"SorUpdateIndicatorList"`
 
	

	UpuInfo *UpuInfo `json:"upuInfo,omitempty" yaml:"upuInfo" bson:"upuInfo" mapstructure:"UpuInfo"`
 
	

	MicoAllowed *bool `json:"micoAllowed,omitempty" yaml:"micoAllowed" bson:"micoAllowed" mapstructure:"MicoAllowed"`
 
	

	SharedAmDataIds *[]string `json:"sharedAmDataIds,omitempty" yaml:"sharedAmDataIds" bson:"sharedAmDataIds" mapstructure:"SharedAmDataIds"`
 
	

	OdbPacketServices *OdbPacketServices `json:"odbPacketServices,omitempty" yaml:"odbPacketServices" bson:"odbPacketServices" mapstructure:"OdbPacketServices"`
 
	

	SubscribedDnnList *[]string `json:"subscribedDnnList,omitempty" yaml:"subscribedDnnList" bson:"subscribedDnnList" mapstructure:"SubscribedDnnList"`
 
	

	ServiceGapTime *int32 `json:"serviceGapTime,omitempty" yaml:"serviceGapTime" bson:"serviceGapTime" mapstructure:"ServiceGapTime"`
 
	

	MdtUserConsent *MdtUserConsent `json:"mdtUserConsent,omitempty" yaml:"mdtUserConsent" bson:"mdtUserConsent" mapstructure:"MdtUserConsent"`
 
	

	MdtConfiguration *MdtConfiguration `json:"mdtConfiguration,omitempty" yaml:"mdtConfiguration" bson:"mdtConfiguration" mapstructure:"MdtConfiguration"`
 
	

	TraceData *TraceData `json:"traceData,omitempty" yaml:"traceData" bson:"traceData" mapstructure:"TraceData"`
 
	

	CagData *CagData `json:"cagData,omitempty" yaml:"cagData" bson:"cagData" mapstructure:"CagData"`
 
	

	StnSr *string `json:"stnSr,omitempty" yaml:"stnSr" bson:"stnSr" mapstructure:"StnSr"`
 
	

	CMsisdn *string `json:"cMsisdn,omitempty" yaml:"cMsisdn" bson:"cMsisdn" mapstructure:"CMsisdn"`
 
	

	NbIoTUePriority *int32 `json:"nbIoTUePriority,omitempty" yaml:"nbIoTUePriority" bson:"nbIoTUePriority" mapstructure:"NbIoTUePriority"`
 
	

	NssaiInclusionAllowed *bool `json:"nssaiInclusionAllowed,omitempty" yaml:"nssaiInclusionAllowed" bson:"nssaiInclusionAllowed" mapstructure:"NssaiInclusionAllowed"`
 
	

	RgWirelineCharacteristics *string `json:"rgWirelineCharacteristics,omitempty" yaml:"rgWirelineCharacteristics" bson:"rgWirelineCharacteristics" mapstructure:"RgWirelineCharacteristics"`
 
	

	EcRestrictionDataWb *EcRestrictionDataWb `json:"ecRestrictionDataWb,omitempty" yaml:"ecRestrictionDataWb" bson:"ecRestrictionDataWb" mapstructure:"EcRestrictionDataWb"`
 
	

	EcRestrictionDataNb *bool `json:"ecRestrictionDataNb,omitempty" yaml:"ecRestrictionDataNb" bson:"ecRestrictionDataNb" mapstructure:"EcRestrictionDataNb"`
 
	

	ExpectedUeBehaviourList *ExpectedUeBehaviourData `json:"expectedUeBehaviourList,omitempty" yaml:"expectedUeBehaviourList" bson:"expectedUeBehaviourList" mapstructure:"ExpectedUeBehaviourList"`
 
	

	PrimaryRatRestrictions *[]RatType `json:"primaryRatRestrictions,omitempty" yaml:"primaryRatRestrictions" bson:"primaryRatRestrictions" mapstructure:"PrimaryRatRestrictions"`
 
	

	SecondaryRatRestrictions *[]RatType `json:"secondaryRatRestrictions,omitempty" yaml:"secondaryRatRestrictions" bson:"secondaryRatRestrictions" mapstructure:"SecondaryRatRestrictions"`
 
	

	EdrxParametersList *[]EdrxParameters `json:"edrxParametersList,omitempty" yaml:"edrxParametersList" bson:"edrxParametersList" mapstructure:"EdrxParametersList"`
 
	

	PtwParametersList *[]PtwParameters `json:"ptwParametersList,omitempty" yaml:"ptwParametersList" bson:"ptwParametersList" mapstructure:"PtwParametersList"`
 
	

	IabOperationAllowed *bool `json:"iabOperationAllowed,omitempty" yaml:"iabOperationAllowed" bson:"iabOperationAllowed" mapstructure:"IabOperationAllowed"`
 
	

	WirelineForbiddenAreas *[]WirelineArea `json:"wirelineForbiddenAreas,omitempty" yaml:"wirelineForbiddenAreas" bson:"wirelineForbiddenAreas" mapstructure:"WirelineForbiddenAreas"`
 
	

	WirelineServiceAreaRestriction *WirelineServiceAreaRestriction `json:"wirelineServiceAreaRestriction,omitempty" yaml:"wirelineServiceAreaRestriction" bson:"wirelineServiceAreaRestriction" mapstructure:"WirelineServiceAreaRestriction"`
}
