/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ReportingTrigger string
// enum type
// List of ReportingTrigger 
const (
	REPORTINGTRIGGER_PERIODICAL ReportingTrigger = "PERIODICAL"
	REPORTINGTRIGGER_EVENT_A2 ReportingTrigger = "EVENT_A2"
	REPORTINGTRIGGER_EVENT_A2_PERIODIC ReportingTrigger = "EVENT_A2_PERIODIC"
	REPORTINGTRIGGER_ALL_RRM_EVENT_TRIGGERS ReportingTrigger = "ALL_RRM_EVENT_TRIGGERS"
)
