/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LcsMoServiceClassAnyOf string

// List of LcsMoServiceClassAnyOf 
const (
	LCSMOSERVICECLASSANYOF_BASIC_SELF_LOCATION LcsMoServiceClassAnyOf = "BASIC_SELF_LOCATION"
	LCSMOSERVICECLASSANYOF_AUTONOMOUS_SELF_LOCATION LcsMoServiceClassAnyOf = "AUTONOMOUS_SELF_LOCATION"
	LCSMOSERVICECLASSANYOF_TRANSFER_TO_THIRD_PARTY LcsMoServiceClassAnyOf = "TRANSFER_TO_THIRD_PARTY"
)
