/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type JobTypeAnyOf string

// List of JobTypeAnyOf 
const (
	JOBTYPEANYOF_IMMEDIATE_MDT_ONLY JobTypeAnyOf = "IMMEDIATE_MDT_ONLY"
	JOBTYPEANYOF_LOGGED_MDT_ONLY JobTypeAnyOf = "LOGGED_MDT_ONLY"
	JOBTYPEANYOF_TRACE_ONLY JobTypeAnyOf = "TRACE_ONLY"
	JOBTYPEANYOF_IMMEDIATE_MDT_AND_TRACE JobTypeAnyOf = "IMMEDIATE_MDT_AND_TRACE"
	JOBTYPEANYOF_RLF_REPORTS_ONLY JobTypeAnyOf = "RLF_REPORTS_ONLY"
	JOBTYPEANYOF_RCEF_REPORTS_ONLY JobTypeAnyOf = "RCEF_REPORTS_ONLY"
	JOBTYPEANYOF_LOGGED_MBSFN_MDT JobTypeAnyOf = "LOGGED_MBSFN_MDT"
)
