/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SubscribedDefaultQos struct {


	
	// simple type
 
	

	Var5qi int32 `json:"5qi" yaml:"5qi" bson:"5qi" mapstructure:"Var5qi"`
 
	

	Arp Arp `json:"arp" yaml:"arp" bson:"arp" mapstructure:"Arp"`
 
	

	PriorityLevel *int32 `json:"priorityLevel,omitempty" yaml:"priorityLevel" bson:"priorityLevel" mapstructure:"PriorityLevel"`
}
