/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ServiceAreaRestriction struct {


	
	// simple type
 
	

	RestrictionType *RestrictionType `json:"restrictionType,omitempty" yaml:"restrictionType" bson:"restrictionType" mapstructure:"RestrictionType"`
 
	

	Areas *[]Area `json:"areas,omitempty" yaml:"areas" bson:"areas" mapstructure:"Areas"`
 
	

	MaxNumOfTAs *int32 `json:"maxNumOfTAs,omitempty" yaml:"maxNumOfTAs" bson:"maxNumOfTAs" mapstructure:"MaxNumOfTAs"`
 
	

	MaxNumOfTAsForNotAllowedAreas *int32 `json:"maxNumOfTAsForNotAllowedAreas,omitempty" yaml:"maxNumOfTAsForNotAllowedAreas" bson:"maxNumOfTAsForNotAllowedAreas" mapstructure:"MaxNumOfTAsForNotAllowedAreas"`
}
