/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UeUpdateStatus string
// enum type
// List of UeUpdateStatus 
const (
	UEUPDATESTATUS_NOT_SENT UeUpdateStatus = "NOT_SENT"
	UEUPDATESTATUS_SENT_NO_ACK_REQUIRED UeUpdateStatus = "SENT_NO_ACK_REQUIRED"
	UEUPDATESTATUS_WAITING_FOR_ACK UeUpdateStatus = "WAITING_FOR_ACK"
	UEUPDATESTATUS_ACK_RECEIVED UeUpdateStatus = "ACK_RECEIVED"
	UEUPDATESTATUS_NEGATIVE_ACK_RECEIVED UeUpdateStatus = "NEGATIVE_ACK_RECEIVED"
)
