/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type AuthEvent struct {


	
	// simple type
 
	

	NfInstanceId string `json:"nfInstanceId" yaml:"nfInstanceId" bson:"nfInstanceId" mapstructure:"NfInstanceId"`
 
	

	Success bool `json:"success" yaml:"success" bson:"success" mapstructure:"Success"`
 
	

	TimeStamp time.Time `json:"timeStamp" yaml:"timeStamp" bson:"timeStamp" mapstructure:"TimeStamp"`
 
	

	AuthType AuthType `json:"authType" yaml:"authType" bson:"authType" mapstructure:"AuthType"`
 
	

	ServingNetworkName string `json:"servingNetworkName" yaml:"servingNetworkName" bson:"servingNetworkName" mapstructure:"ServingNetworkName"`
 
	

	AuthRemovalInd *bool `json:"authRemovalInd,omitempty" yaml:"authRemovalInd" bson:"authRemovalInd" mapstructure:"AuthRemovalInd"`
}
