/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type Guami struct {


	
	// simple type
 
	

	PlmnId PlmnIdNid `json:"plmnId" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	AmfId string `json:"amfId" yaml:"amfId" bson:"amfId" mapstructure:"AmfId"`
}
