/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// UePolicySet - Contains the UE policy data for a given subscriber.
type UePolicySet struct {


	
	// simple type
 
	

	PraInfos *map[string]PresenceInfo `json:"praInfos,omitempty" yaml:"praInfos" bson:"praInfos" mapstructure:"PraInfos"`
 
	

	SubscCats *[]string `json:"subscCats,omitempty" yaml:"subscCats" bson:"subscCats" mapstructure:"SubscCats"`
 
	

	UePolicySections *map[string]UePolicySection `json:"uePolicySections,omitempty" yaml:"uePolicySections" bson:"uePolicySections" mapstructure:"UePolicySections"`
 
	

	Upsis *[]string `json:"upsis,omitempty" yaml:"upsis" bson:"upsis" mapstructure:"Upsis"`
 
	

	AllowedRouteSelDescs *map[string]PlmnRouteSelectionDescriptor `json:"allowedRouteSelDescs,omitempty" yaml:"allowedRouteSelDescs" bson:"allowedRouteSelDescs" mapstructure:"AllowedRouteSelDescs"`
 
	

	AndspInd *bool `json:"andspInd,omitempty" yaml:"andspInd" bson:"andspInd" mapstructure:"AndspInd"`
 
	

	Pei *string `json:"pei,omitempty" yaml:"pei" bson:"pei" mapstructure:"Pei"`
 
	

	OsIds *[]string `json:"osIds,omitempty" yaml:"osIds" bson:"osIds" mapstructure:"OsIds"`
 
	

	SuppFeat *string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat" mapstructure:"SuppFeat"`
}
