/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DataInd string
// enum type
// List of DataInd 
const (
	DATAIND_PFD DataInd = "PFD"
	DATAIND_IPTV DataInd = "IPTV"
	DATAIND_BDT DataInd = "BDT"
	DATAIND_SVC_PARAM DataInd = "SVC_PARAM"
)
