/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EpsInterworkingInfo struct {


	
	// simple type

	// A map (list of key-value pairs where Dnn serves as key) of EpsIwkPgws 
	

	EpsIwkPgws *map[string]EpsIwkPgw `json:"epsIwkPgws,omitempty" yaml:"epsIwkPgws" bson:"epsIwkPgws" mapstructure:"EpsIwkPgws"`
}
