/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type CommunicationCharacteristics struct {


	
	// simple type
 
	

	PpSubsRegTimer *PpSubsRegTimer `json:"ppSubsRegTimer,omitempty" yaml:"ppSubsRegTimer" bson:"ppSubsRegTimer" mapstructure:"PpSubsRegTimer"`
 
	

	PpActiveTime *PpActiveTime `json:"ppActiveTime,omitempty" yaml:"ppActiveTime" bson:"ppActiveTime" mapstructure:"PpActiveTime"`
 
	

	PpDlPacketCount *int32 `json:"ppDlPacketCount,omitempty" yaml:"ppDlPacketCount" bson:"ppDlPacketCount" mapstructure:"PpDlPacketCount"`
 
	

	PpDlPacketCountExt *PpDlPacketCountExt `json:"ppDlPacketCountExt,omitempty" yaml:"ppDlPacketCountExt" bson:"ppDlPacketCountExt" mapstructure:"PpDlPacketCountExt"`
 
	

	PpMaximumResponseTime *PpMaximumResponseTime `json:"ppMaximumResponseTime,omitempty" yaml:"ppMaximumResponseTime" bson:"ppMaximumResponseTime" mapstructure:"PpMaximumResponseTime"`
 
	

	PpMaximumLatency *PpMaximumLatency `json:"ppMaximumLatency,omitempty" yaml:"ppMaximumLatency" bson:"ppMaximumLatency" mapstructure:"PpMaximumLatency"`
}
