/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ReportIntervalNrMdtAnyOf string

// List of ReportIntervalNrMdtAnyOf 
const (
	REPORTINTERVALNRMDTANYOF__120 ReportIntervalNrMdtAnyOf = "120"
	REPORTINTERVALNRMDTANYOF__240 ReportIntervalNrMdtAnyOf = "240"
	REPORTINTERVALNRMDTANYOF__480 ReportIntervalNrMdtAnyOf = "480"
	REPORTINTERVALNRMDTANYOF__640 ReportIntervalNrMdtAnyOf = "640"
	REPORTINTERVALNRMDTANYOF__1024 ReportIntervalNrMdtAnyOf = "1024"
	REPORTINTERVALNRMDTANYOF__2048 ReportIntervalNrMdtAnyOf = "2048"
	REPORTINTERVALNRMDTANYOF__5120 ReportIntervalNrMdtAnyOf = "5120"
	REPORTINTERVALNRMDTANYOF__10240 ReportIntervalNrMdtAnyOf = "10240"
	REPORTINTERVALNRMDTANYOF__20480 ReportIntervalNrMdtAnyOf = "20480"
	REPORTINTERVALNRMDTANYOF__40960 ReportIntervalNrMdtAnyOf = "40960"
	REPORTINTERVALNRMDTANYOF__60000 ReportIntervalNrMdtAnyOf = "60000"
	REPORTINTERVALNRMDTANYOF__360000 ReportIntervalNrMdtAnyOf = "360000"
	REPORTINTERVALNRMDTANYOF__720000 ReportIntervalNrMdtAnyOf = "720000"
	REPORTINTERVALNRMDTANYOF__1800000 ReportIntervalNrMdtAnyOf = "1800000"
	REPORTINTERVALNRMDTANYOF__3600000 ReportIntervalNrMdtAnyOf = "3600000"
)
