/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ReportIntervalMdtAnyOf string

// List of ReportIntervalMdtAnyOf 
const (
	REPORTINTERVALMDTANYOF__120 ReportIntervalMdtAnyOf = "120"
	REPORTINTERVALMDTANYOF__240 ReportIntervalMdtAnyOf = "240"
	REPORTINTERVALMDTANYOF__480 ReportIntervalMdtAnyOf = "480"
	REPORTINTERVALMDTANYOF__640 ReportIntervalMdtAnyOf = "640"
	REPORTINTERVALMDTANYOF__1024 ReportIntervalMdtAnyOf = "1024"
	REPORTINTERVALMDTANYOF__2048 ReportIntervalMdtAnyOf = "2048"
	REPORTINTERVALMDTANYOF__5120 ReportIntervalMdtAnyOf = "5120"
	REPORTINTERVALMDTANYOF__10240 ReportIntervalMdtAnyOf = "10240"
	REPORTINTERVALMDTANYOF__60000 ReportIntervalMdtAnyOf = "60000"
	REPORTINTERVALMDTANYOF__360000 ReportIntervalMdtAnyOf = "360000"
	REPORTINTERVALMDTANYOF__720000 ReportIntervalMdtAnyOf = "720000"
	REPORTINTERVALMDTANYOF__1800000 ReportIntervalMdtAnyOf = "1800000"
	REPORTINTERVALMDTANYOF__3600000 ReportIntervalMdtAnyOf = "3600000"
)
