/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LcsPrivacy struct {


	
	// simple type
 
	

	AfInstanceId *string `json:"afInstanceId,omitempty" yaml:"afInstanceId" bson:"afInstanceId" mapstructure:"AfInstanceId"`
 
	

	ReferenceId *int32 `json:"referenceId,omitempty" yaml:"referenceId" bson:"referenceId" mapstructure:"ReferenceId"`
 
	

	Lpi *Lpi `json:"lpi,omitempty" yaml:"lpi" bson:"lpi" mapstructure:"Lpi"`
 
	

	MtcProviderInformation *string `json:"mtcProviderInformation,omitempty" yaml:"mtcProviderInformation" bson:"mtcProviderInformation" mapstructure:"MtcProviderInformation"`
}
