/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type TimeWindow struct {


	
	// simple type

	// string with format \"date-time\" as defined in OpenAPI. 
	

	StartTime string `json:"startTime" yaml:"startTime" bson:"startTime" mapstructure:"StartTime"`

	// string with format \"date-time\" as defined in OpenAPI. 
	

	StopTime string `json:"stopTime" yaml:"stopTime" bson:"stopTime" mapstructure:"StopTime"`
}
