/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// SmPolicyDnnData - Contains the SM policy data for a given DNN (and S-NSSAI).
type SmPolicyDnnData struct {


	
	// simple type
 
	

	Dnn string `json:"dnn" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	AllowedServices *[]string `json:"allowedServices,omitempty" yaml:"allowedServices" bson:"allowedServices" mapstructure:"AllowedServices"`
 
	

	SubscCats *[]string `json:"subscCats,omitempty" yaml:"subscCats" bson:"subscCats" mapstructure:"SubscCats"`
 
	

	GbrUl *string `json:"gbrUl,omitempty" yaml:"gbrUl" bson:"gbrUl" mapstructure:"GbrUl"`
 
	

	GbrDl *string `json:"gbrDl,omitempty" yaml:"gbrDl" bson:"gbrDl" mapstructure:"GbrDl"`
 
	

	AdcSupport *bool `json:"adcSupport,omitempty" yaml:"adcSupport" bson:"adcSupport" mapstructure:"AdcSupport"`
 
	

	SubscSpendingLimits *bool `json:"subscSpendingLimits,omitempty" yaml:"subscSpendingLimits" bson:"subscSpendingLimits" mapstructure:"SubscSpendingLimits"`
 
	

	Ipv4Index *int32 `json:"ipv4Index,omitempty" yaml:"ipv4Index" bson:"ipv4Index" mapstructure:"Ipv4Index"`
 
	

	Ipv6Index *int32 `json:"ipv6Index,omitempty" yaml:"ipv6Index" bson:"ipv6Index" mapstructure:"Ipv6Index"`
 
	

	Offline *bool `json:"offline,omitempty" yaml:"offline" bson:"offline" mapstructure:"Offline"`
 
	

	Online *bool `json:"online,omitempty" yaml:"online" bson:"online" mapstructure:"Online"`
 
	

	ChfInfo *ChargingInformation `json:"chfInfo,omitempty" yaml:"chfInfo" bson:"chfInfo" mapstructure:"ChfInfo"`
 
	

	RefUmDataLimitIds *map[string]LimitIdToMonitoringKey `json:"refUmDataLimitIds,omitempty" yaml:"refUmDataLimitIds" bson:"refUmDataLimitIds" mapstructure:"RefUmDataLimitIds"`
 
	

	MpsPriority *bool `json:"mpsPriority,omitempty" yaml:"mpsPriority" bson:"mpsPriority" mapstructure:"MpsPriority"`
 
	

	McsPriority *bool `json:"mcsPriority,omitempty" yaml:"mcsPriority" bson:"mcsPriority" mapstructure:"McsPriority"`
 
	

	ImsSignallingPrio *bool `json:"imsSignallingPrio,omitempty" yaml:"imsSignallingPrio" bson:"imsSignallingPrio" mapstructure:"ImsSignallingPrio"`
 
	

	MpsPriorityLevel *int32 `json:"mpsPriorityLevel,omitempty" yaml:"mpsPriorityLevel" bson:"mpsPriorityLevel" mapstructure:"MpsPriorityLevel"`
 
	

	McsPriorityLevel *int32 `json:"mcsPriorityLevel,omitempty" yaml:"mcsPriorityLevel" bson:"mcsPriorityLevel" mapstructure:"McsPriorityLevel"`
 
	

	PraInfos *map[string]PresenceInfo `json:"praInfos,omitempty" yaml:"praInfos" bson:"praInfos" mapstructure:"PraInfos"`
 
	

	BdtRefIds *map[string]string `json:"bdtRefIds,omitempty" yaml:"bdtRefIds" bson:"bdtRefIds" mapstructure:"BdtRefIds"`
 
	

	LocRoutNotAllowed *bool `json:"locRoutNotAllowed,omitempty" yaml:"locRoutNotAllowed" bson:"locRoutNotAllowed" mapstructure:"LocRoutNotAllowed"`
}
