/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PlmnEcInfo struct {


	
	// simple type
 
	

	PlmnId PlmnId `json:"plmnId" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	EcRestrictionDataWb *EcRestrictionDataWb `json:"ecRestrictionDataWb,omitempty" yaml:"ecRestrictionDataWb" bson:"ecRestrictionDataWb" mapstructure:"EcRestrictionDataWb"`
 
	

	EcRestrictionDataNb *bool `json:"ecRestrictionDataNb,omitempty" yaml:"ecRestrictionDataNb" bson:"ecRestrictionDataNb" mapstructure:"EcRestrictionDataNb"`
}
