/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type InvalidParam struct {


	
	// simple type
 
	

	Param string `json:"param" yaml:"param" bson:"param" mapstructure:"Param"`
 
	

	Reason *string `json:"reason,omitempty" yaml:"reason" bson:"reason" mapstructure:"Reason"`
}
