/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CollectionPeriodRmmNrMdtAnyOf string

// List of CollectionPeriodRmmNrMdtAnyOf 
const (
	COLLECTIONPERIODRMMNRMDTANYOF__1024 CollectionPeriodRmmNrMdtAnyOf = "1024"
	COLLECTIONPERIODRMMNRMDTANYOF__2048 CollectionPeriodRmmNrMdtAnyOf = "2048"
	COLLECTIONPERIODRMMNRMDTANYOF__5120 CollectionPeriodRmmNrMdtAnyOf = "5120"
	COLLECTIONPERIODRMMNRMDTANYOF__10240 CollectionPeriodRmmNrMdtAnyOf = "10240"
	COLLECTIONPERIODRMMNRMDTANYOF__60000 CollectionPeriodRmmNrMdtAnyOf = "60000"
)
