/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type JobType string
// enum type
// List of JobType 
const (
	JOBTYPE_IMMEDIATE_MDT_ONLY JobType = "IMMEDIATE_MDT_ONLY"
	JOBTYPE_LOGGED_MDT_ONLY JobType = "LOGGED_MDT_ONLY"
	JOBTYPE_TRACE_ONLY JobType = "TRACE_ONLY"
	JOBTYPE_IMMEDIATE_MDT_AND_TRACE JobType = "IMMEDIATE_MDT_AND_TRACE"
	JOBTYPE_RLF_REPORTS_ONLY JobType = "RLF_REPORTS_ONLY"
	JOBTYPE_RCEF_REPORTS_ONLY JobType = "RCEF_REPORTS_ONLY"
	JOBTYPE_LOGGED_MBSFN_MDT JobType = "LOGGED_MBSFN_MDT"
)
