/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// GeographicArea struct for GeographicArea
type GeographicArea struct {
	// any of type
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	EllipsoidArc *EllipsoidArc
	
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	Point *Point
	
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	PointAltitude *PointAltitude
	
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	PointAltitudeUncertainty *PointAltitudeUncertainty
	
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	PointUncertaintyCircle *PointUncertaintyCircle
	
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	PointUncertaintyEllipse *PointUncertaintyEllipse
	
	
	// GeographicArea anyOf<Point,PointUncertaintyCircle,PointUncertaintyEllipse,Polygon,PointAltitude,PointAltitudeUncertainty,EllipsoidArc>
		// base name 
	// complexType=
	// datatypeWithEnum 
	// dataFormat
	// baseType
	// containerType
	Polygon *Polygon
	
}

