/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type SmfRegistration struct {


	
	// simple type
 
	

	SmfInstanceId string `json:"smfInstanceId" yaml:"smfInstanceId" bson:"smfInstanceId" mapstructure:"SmfInstanceId"`
 
	

	SmfSetId *string `json:"smfSetId,omitempty" yaml:"smfSetId" bson:"smfSetId" mapstructure:"SmfSetId"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
 
	

	PduSessionId int32 `json:"pduSessionId" yaml:"pduSessionId" bson:"pduSessionId" mapstructure:"PduSessionId"`
 
	

	SingleNssai Snssai `json:"singleNssai" yaml:"singleNssai" bson:"singleNssai" mapstructure:"SingleNssai"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	EmergencyServices *bool `json:"emergencyServices,omitempty" yaml:"emergencyServices" bson:"emergencyServices" mapstructure:"EmergencyServices"`
 
	

	PcscfRestorationCallbackUri *string `json:"pcscfRestorationCallbackUri,omitempty" yaml:"pcscfRestorationCallbackUri" bson:"pcscfRestorationCallbackUri" mapstructure:"PcscfRestorationCallbackUri"`
 
	

	PlmnId PlmnId `json:"plmnId" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	PgwFqdn *string `json:"pgwFqdn,omitempty" yaml:"pgwFqdn" bson:"pgwFqdn" mapstructure:"PgwFqdn"`
 
	

	EpdgInd *bool `json:"epdgInd,omitempty" yaml:"epdgInd" bson:"epdgInd" mapstructure:"EpdgInd"`
 
	

	DeregCallbackUri *string `json:"deregCallbackUri,omitempty" yaml:"deregCallbackUri" bson:"deregCallbackUri" mapstructure:"DeregCallbackUri"`
 
	

	RegistrationReason *RegistrationReason `json:"registrationReason,omitempty" yaml:"registrationReason" bson:"registrationReason" mapstructure:"RegistrationReason"`
 
	

	RegistrationTime *time.Time `json:"registrationTime,omitempty" yaml:"registrationTime" bson:"registrationTime" mapstructure:"RegistrationTime"`
 
	

	ContextInfo *ContextInfo `json:"contextInfo,omitempty" yaml:"contextInfo" bson:"contextInfo" mapstructure:"ContextInfo"`
}
