/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


// UsageMonData - Contains remain allowed usage data for a subscriber.
type UsageMonData struct {


	
	// simple type
 
	

	LimitId string `json:"limitId" yaml:"limitId" bson:"limitId" mapstructure:"LimitId"`
 
	

	Scopes *map[string]UsageMonDataScope `json:"scopes,omitempty" yaml:"scopes" bson:"scopes" mapstructure:"Scopes"`
 
	

	UmLevel *UsageMonLevel `json:"umLevel,omitempty" yaml:"umLevel" bson:"umLevel" mapstructure:"UmLevel"`
 
	

	AllowedUsage *UsageThreshold `json:"allowedUsage,omitempty" yaml:"allowedUsage" bson:"allowedUsage" mapstructure:"AllowedUsage"`
 
	

	ResetTime *time.Time `json:"resetTime,omitempty" yaml:"resetTime" bson:"resetTime" mapstructure:"ResetTime"`
 
	

	SuppFeat *string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat" mapstructure:"SuppFeat"`
}
