/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ReportTypeMdt string
// enum type
// List of ReportTypeMdt 
const (
	REPORTTYPEMDT_PERIODICAL ReportTypeMdt = "PERIODICAL"
	REPORTTYPEMDT_EVENT_TRIGGED ReportTypeMdt = "EVENT_TRIGGED"
)
