/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PduSessionContinuityInd string
// enum type
// List of PduSessionContinuityInd 
const (
	PDUSESSIONCONTINUITYIND_MAINTAIN_PDUSESSION PduSessionContinuityInd = "MAINTAIN_PDUSESSION"
	PDUSESSIONCONTINUITYIND_RECONNECT_PDUSESSION PduSessionContinuityInd = "RECONNECT_PDUSESSION"
	PDUSESSIONCONTINUITYIND_RELEASE_PDUSESSION PduSessionContinuityInd = "RELEASE_PDUSESSION"
)
