/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UpuData1 struct {


	
	// simple type
 
	

	SecPacket *string `json:"secPacket,omitempty" yaml:"secPacket" bson:"secPacket" mapstructure:"SecPacket"`
 
	

	DefaultConfNssai *[]Snssai `json:"defaultConfNssai,omitempty" yaml:"defaultConfNssai" bson:"defaultConfNssai" mapstructure:"DefaultConfNssai"`
 
	

	RoutingId *string `json:"routingId,omitempty" yaml:"routingId" bson:"routingId" mapstructure:"RoutingId"`
}
