/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DnaiChangeType string
// enum type
// List of DnaiChangeType 
const (
	DNAICHANGETYPE_EARLY DnaiChangeType = "EARLY"
	DNAICHANGETYPE_EARLY_LATE DnaiChangeType = "EARLY_LATE"
	DNAICHANGETYPE_LATE DnaiChangeType = "LATE"
)
