/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AppPortId struct {


	
	// simple type
 
	

	DestinationPort *int32 `json:"destinationPort,omitempty" yaml:"destinationPort" bson:"destinationPort" mapstructure:"DestinationPort"`
 
	

	OriginatorPort *int32 `json:"originatorPort,omitempty" yaml:"originatorPort" bson:"originatorPort" mapstructure:"OriginatorPort"`
}
