/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SmfRegList struct {


	
	// simple type
	// parent
 
	
	// not map
	// is array
	//	Items []SmfRegistration
 Items *[]SmfRegistration `json:"Items,omitempty" yaml:"items" bson:"items" mapstructure:"Items"`

}
