/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type FlowDirection string
// enum type
// List of FlowDirection 
const (
	FLOWDIRECTION_DOWNLINK FlowDirection = "DOWNLINK"
	FLOWDIRECTION_UPLINK FlowDirection = "UPLINK"
	FLOWDIRECTION_BIDIRECTIONAL FlowDirection = "BIDIRECTIONAL"
	FLOWDIRECTION_UNSPECIFIED FlowDirection = "UNSPECIFIED"
)
