/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AcsInfoRm struct {

	AcsUrl string `json:"acsUrl,omitempty" yaml:"acsUrl" bson:"acsUrl" mapstructure:"AcsUrl"`

	AcsIpv4Addr string `json:"acsIpv4Addr,omitempty" yaml:"acsIpv4Addr" bson:"acsIpv4Addr" mapstructure:"AcsIpv4Addr"`

	AcsIpv6Addr Ipv6Addr `json:"acsIpv6Addr,omitempty" yaml:"acsIpv6Addr" bson:"acsIpv6Addr" mapstructure:"AcsIpv6Addr"`
}
