/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PpDataTypeAnyOf string

// List of PpDataTypeAnyOf 
const (
	PPDATATYPEANYOF_COMMUNICATION_CHARACTERISTICS PpDataTypeAnyOf = "COMMUNICATION_CHARACTERISTICS"
	PPDATATYPEANYOF_EXPECTED_UE_BEHAVIOUR PpDataTypeAnyOf = "EXPECTED_UE_BEHAVIOUR"
	PPDATATYPEANYOF_EC_RESTRICTION PpDataTypeAnyOf = "EC_RESTRICTION"
	PPDATATYPEANYOF_ACS_INFO PpDataTypeAnyOf = "ACS_INFO"
	PPDATATYPEANYOF_TRACE PpDataTypeAnyOf = "TRACE"
	PPDATATYPEANYOF_STN_SR PpDataTypeAnyOf = "STN_SR"
	PPDATATYPEANYOF_LCS_PRIVACY PpDataTypeAnyOf = "LCS_PRIVACY"
	PPDATATYPEANYOF_SOR_INFO PpDataTypeAnyOf = "SOR_INFO"
)
