/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type Model5GvnGroupData struct {


	
	// simple type
 
	

	Dnn string `json:"dnn" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	SNssai Snssai `json:"sNssai" yaml:"sNssai" bson:"sNssai" mapstructure:"SNssai"`
 
	

	PduSessionTypes *[]PduSessionType `json:"pduSessionTypes,omitempty" yaml:"pduSessionTypes" bson:"pduSessionTypes" mapstructure:"PduSessionTypes"`
 
	

	AppDescriptors *[]AppDescriptor `json:"appDescriptors,omitempty" yaml:"appDescriptors" bson:"appDescriptors" mapstructure:"AppDescriptors"`
 
	

	SecondaryAuth *bool `json:"secondaryAuth,omitempty" yaml:"secondaryAuth" bson:"secondaryAuth" mapstructure:"SecondaryAuth"`
 
	

	DnAaaAddress *IpAddress `json:"dnAaaAddress,omitempty" yaml:"dnAaaAddress" bson:"dnAaaAddress" mapstructure:"DnAaaAddress"`
}
