/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type MonitoringConfiguration struct {


	
	// simple type
 
	

	EventType EventType `json:"eventType" yaml:"eventType" bson:"eventType" mapstructure:"EventType"`
 
	

	ImmediateFlag *bool `json:"immediateFlag,omitempty" yaml:"immediateFlag" bson:"immediateFlag" mapstructure:"ImmediateFlag"`
 
	

	LocationReportingConfiguration *LocationReportingConfiguration `json:"locationReportingConfiguration,omitempty" yaml:"locationReportingConfiguration" bson:"locationReportingConfiguration" mapstructure:"LocationReportingConfiguration"`
 
	

	AssociationType *AssociationType `json:"associationType,omitempty" yaml:"associationType" bson:"associationType" mapstructure:"AssociationType"`
 
	

	DatalinkReportCfg *DatalinkReportingConfiguration `json:"datalinkReportCfg,omitempty" yaml:"datalinkReportCfg" bson:"datalinkReportCfg" mapstructure:"DatalinkReportCfg"`
 
	

	LossConnectivityCfg *LossConnectivityCfg `json:"lossConnectivityCfg,omitempty" yaml:"lossConnectivityCfg" bson:"lossConnectivityCfg" mapstructure:"LossConnectivityCfg"`
 
	

	MaximumLatency *int32 `json:"maximumLatency,omitempty" yaml:"maximumLatency" bson:"maximumLatency" mapstructure:"MaximumLatency"`
 
	

	MaximumResponseTime *int32 `json:"maximumResponseTime,omitempty" yaml:"maximumResponseTime" bson:"maximumResponseTime" mapstructure:"MaximumResponseTime"`
 
	

	SuggestedPacketNumDl *int32 `json:"suggestedPacketNumDl,omitempty" yaml:"suggestedPacketNumDl" bson:"suggestedPacketNumDl" mapstructure:"SuggestedPacketNumDl"`
 
	

	PduSessionStatusCfg *PduSessionStatusCfg `json:"pduSessionStatusCfg,omitempty" yaml:"pduSessionStatusCfg" bson:"pduSessionStatusCfg" mapstructure:"PduSessionStatusCfg"`
 
	

	ReachabilityForSmsCfg *ReachabilityForSmsConfiguration `json:"reachabilityForSmsCfg,omitempty" yaml:"reachabilityForSmsCfg" bson:"reachabilityForSmsCfg" mapstructure:"ReachabilityForSmsCfg"`
 
	

	MtcProviderInformation *string `json:"mtcProviderInformation,omitempty" yaml:"mtcProviderInformation" bson:"mtcProviderInformation" mapstructure:"MtcProviderInformation"`
 
	

	AfId *string `json:"afId,omitempty" yaml:"afId" bson:"afId" mapstructure:"AfId"`
 
	

	IdleStatusInd *bool `json:"idleStatusInd,omitempty" yaml:"idleStatusInd" bson:"idleStatusInd" mapstructure:"IdleStatusInd"`
}
