/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PositioningMethodMdt string
// enum type
// List of PositioningMethodMdt 
const (
	POSITIONINGMETHODMDT_GNSS PositioningMethodMdt = "GNSS"
	POSITIONINGMETHODMDT_E_CELL_ID PositioningMethodMdt = "E_CELL_ID"
)
