/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SorUpdateIndicator string
// enum type
// List of SorUpdateIndicator 
const (
	SORUPDATEINDICATOR_INITIAL_REGISTRATION SorUpdateIndicator = "INITIAL_REGISTRATION"
	SORUPDATEINDICATOR_EMERGENCY_REGISTRATION SorUpdateIndicator = "EMERGENCY_REGISTRATION"
)
