/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// UePolicySection - Contains the UE policy section.
type UePolicySection struct {


	
	// simple type
 
	

	UePolicySectionInfo string `json:"uePolicySectionInfo" yaml:"uePolicySectionInfo" bson:"uePolicySectionInfo" mapstructure:"UePolicySectionInfo"`
 
	

	Upsi string `json:"upsi" yaml:"upsi" bson:"upsi" mapstructure:"Upsi"`
}
