/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DatalinkReportingConfiguration struct {


	
	// simple type
 
	

	DddTrafficDes *[]DddTrafficDescriptor `json:"dddTrafficDes,omitempty" yaml:"dddTrafficDes" bson:"dddTrafficDes" mapstructure:"DddTrafficDes"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	Slice *Snssai `json:"slice,omitempty" yaml:"slice" bson:"slice" mapstructure:"Slice"`
 
	

	DddStatusList *[]DlDataDeliveryStatus `json:"dddStatusList,omitempty" yaml:"dddStatusList" bson:"dddStatusList" mapstructure:"DddStatusList"`
}
