/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// SnssaiRouteSelectionDescriptor - Contains the route selector parameters (DNNs, PDU session types, SSC modes and ATSSS information) per SNSSAI
type SnssaiRouteSelectionDescriptor struct {


	
	// simple type
 
	

	Snssai Snssai `json:"snssai" yaml:"snssai" bson:"snssai" mapstructure:"Snssai"`
 
	

	DnnRouteSelDescs *[]DnnRouteSelectionDescriptor `json:"dnnRouteSelDescs,omitempty" yaml:"dnnRouteSelDescs" bson:"dnnRouteSelDescs" mapstructure:"DnnRouteSelDescs"`
}
