/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type PduSessionManagementData struct {


	
	// simple type
 
	

	PduSessionStatus *PduSessionStatus `json:"pduSessionStatus,omitempty" yaml:"pduSessionStatus" bson:"pduSessionStatus" mapstructure:"PduSessionStatus"`
 
	

	PduSessionStatusTs *time.Time `json:"pduSessionStatusTs,omitempty" yaml:"pduSessionStatusTs" bson:"pduSessionStatusTs" mapstructure:"PduSessionStatusTs"`
 
	

	Dnai *string `json:"dnai,omitempty" yaml:"dnai" bson:"dnai" mapstructure:"Dnai"`
 
	

	DnaiTs *time.Time `json:"dnaiTs,omitempty" yaml:"dnaiTs" bson:"dnaiTs" mapstructure:"DnaiTs"`
 
	

	N6TrafficRoutingInfo *[]RouteToLocation `json:"n6TrafficRoutingInfo,omitempty" yaml:"n6TrafficRoutingInfo" bson:"n6TrafficRoutingInfo" mapstructure:"N6TrafficRoutingInfo"`
 
	

	N6TrafficRoutingInfoTs *time.Time `json:"n6TrafficRoutingInfoTs,omitempty" yaml:"n6TrafficRoutingInfoTs" bson:"n6TrafficRoutingInfoTs" mapstructure:"N6TrafficRoutingInfoTs"`
 
	

	Ipv4Addr *string `json:"ipv4Addr,omitempty" yaml:"ipv4Addr" bson:"ipv4Addr" mapstructure:"Ipv4Addr"`

	// UE IPv6 prefix. 
	

	Ipv6Prefix *[]Ipv6Prefix `json:"ipv6Prefix,omitempty" yaml:"ipv6Prefix" bson:"ipv6Prefix" mapstructure:"Ipv6Prefix"`
 
	

	Ipv6Addrs *[]Ipv6Addr `json:"ipv6Addrs,omitempty" yaml:"ipv6Addrs" bson:"ipv6Addrs" mapstructure:"Ipv6Addrs"`
 
	

	PduSessType *PduSessionType `json:"pduSessType,omitempty" yaml:"pduSessType" bson:"pduSessType" mapstructure:"PduSessType"`
 
	

	IpAddrTs *time.Time `json:"ipAddrTs,omitempty" yaml:"ipAddrTs" bson:"ipAddrTs" mapstructure:"IpAddrTs"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	PduSessionId *int32 `json:"pduSessionId,omitempty" yaml:"pduSessionId" bson:"pduSessionId" mapstructure:"PduSessionId"`
 
	

	SuppFeat *string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat" mapstructure:"SuppFeat"`
}
