/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// TimePeriod - Contains the periodicity for the defined usage monitoring data limits.
type TimePeriod struct {


	
	// simple type
 
	

	Period Periodicity `json:"period" yaml:"period" bson:"period" mapstructure:"Period"`
 
	

	MaxNumPeriod *int32 `json:"maxNumPeriod,omitempty" yaml:"maxNumPeriod" bson:"maxNumPeriod" mapstructure:"MaxNumPeriod"`
}
