/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AccessTechAnyOf string

// List of AccessTechAnyOf 
const (
	ACCESSTECHANYOF_NR AccessTechAnyOf = "NR"
	ACCESSTECHANYOF_EUTRAN_IN_WBS1_MODE_AND_NBS1_MODE AccessTechAnyOf = "EUTRAN_IN_WBS1_MODE_AND_NBS1_MODE"
	ACCESSTECHANYOF_EUTRAN_IN_NBS1_MODE_ONLY AccessTechAnyOf = "EUTRAN_IN_NBS1_MODE_ONLY"
	ACCESSTECHANYOF_EUTRAN_IN_WBS1_MODE_ONLY AccessTechAnyOf = "EUTRAN_IN_WBS1_MODE_ONLY"
	ACCESSTECHANYOF_UTRAN AccessTechAnyOf = "UTRAN"
	ACCESSTECHANYOF_GSM_AND_ECGSM_IO_T AccessTechAnyOf = "GSM_AND_ECGSM_IoT"
	ACCESSTECHANYOF_GSM_WITHOUT_ECGSM_IO_T AccessTechAnyOf = "GSM_WITHOUT_ECGSM_IoT"
	ACCESSTECHANYOF_ECGSM_IO_T_ONLY AccessTechAnyOf = "ECGSM_IoT_ONLY"
	ACCESSTECHANYOF_CDMA_1X_RTT AccessTechAnyOf = "CDMA_1xRTT"
	ACCESSTECHANYOF_CDMA_HRPD AccessTechAnyOf = "CDMA_HRPD"
	ACCESSTECHANYOF_GSM_COMPACT AccessTechAnyOf = "GSM_COMPACT"
)
