/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ExposureDataChangeNotification struct {


	
	// simple type
 
	

	UeId *string `json:"ueId,omitempty" yaml:"ueId" bson:"ueId" mapstructure:"UeId"`
 
	

	AccessAndMobilityData *AccessAndMobilityData `json:"accessAndMobilityData,omitempty" yaml:"accessAndMobilityData" bson:"accessAndMobilityData" mapstructure:"AccessAndMobilityData"`
 
	

	PduSessionManagementData *[]PduSessionManagementData `json:"pduSessionManagementData,omitempty" yaml:"pduSessionManagementData" bson:"pduSessionManagementData" mapstructure:"PduSessionManagementData"`
 
	

	DelResources *[]string `json:"delResources,omitempty" yaml:"delResources" bson:"delResources" mapstructure:"DelResources"`
}
