/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type MeasurementLteForMdtAnyOf string

// List of MeasurementLteForMdtAnyOf 
const (
	MEASUREMENTLTEFORMDTANYOF_M1 MeasurementLteForMdtAnyOf = "M1"
	MEASUREMENTLTEFORMDTANYOF_M2 MeasurementLteForMdtAnyOf = "M2"
	MEASUREMENTLTEFORMDTANYOF_M3 MeasurementLteForMdtAnyOf = "M3"
	MEASUREMENTLTEFORMDTANYOF_M4_DL MeasurementLteForMdtAnyOf = "M4_DL"
	MEASUREMENTLTEFORMDTANYOF_M4_UL MeasurementLteForMdtAnyOf = "M4_UL"
	MEASUREMENTLTEFORMDTANYOF_M5_DL MeasurementLteForMdtAnyOf = "M5_DL"
	MEASUREMENTLTEFORMDTANYOF_M5_UL MeasurementLteForMdtAnyOf = "M5_UL"
	MEASUREMENTLTEFORMDTANYOF_M6_DL MeasurementLteForMdtAnyOf = "M6_DL"
	MEASUREMENTLTEFORMDTANYOF_M6_UL MeasurementLteForMdtAnyOf = "M6_UL"
	MEASUREMENTLTEFORMDTANYOF_M7_DL MeasurementLteForMdtAnyOf = "M7_DL"
	MEASUREMENTLTEFORMDTANYOF_M7_UL MeasurementLteForMdtAnyOf = "M7_UL"
	MEASUREMENTLTEFORMDTANYOF_M8 MeasurementLteForMdtAnyOf = "M8"
	MEASUREMENTLTEFORMDTANYOF_M9 MeasurementLteForMdtAnyOf = "M9"
)
