/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type SensorMeasurement string
// enum type
// List of SensorMeasurement 
const (
	SENSORMEASUREMENT_BAROMETRIC_PRESSURE SensorMeasurement = "BAROMETRIC_PRESSURE"
	SENSORMEASUREMENT_UE_SPEED SensorMeasurement = "UE_SPEED"
	SENSORMEASUREMENT_UE_ORIENTATION SensorMeasurement = "UE_ORIENTATION"
)
