/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type NetworkNodeDiameterAddress struct {


	
	// simple type
 
	

	Name string `json:"name" yaml:"name" bson:"name" mapstructure:"Name"`
 
	

	Realm string `json:"realm" yaml:"realm" bson:"realm" mapstructure:"Realm"`
}
