/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// DnnRouteSelectionDescriptor - Contains the route selector parameters (PDU session types, SSC modes and ATSSS information) per DNN
type DnnRouteSelectionDescriptor struct {


	
	// simple type
 
	

	Dnn string `json:"dnn" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	SscModes *[]SscMode `json:"sscModes,omitempty" yaml:"sscModes" bson:"sscModes" mapstructure:"SscModes"`
 
	

	PduSessTypes *[]PduSessionType `json:"pduSessTypes,omitempty" yaml:"pduSessTypes" bson:"pduSessTypes" mapstructure:"PduSessTypes"`

	// Indicates whether MA PDU session establishment is allowed for this DNN. When set to value true MA PDU session establishment is allowed for this DNN. 
	

	AtsssInfo *bool `json:"atsssInfo,omitempty" yaml:"atsssInfo" bson:"atsssInfo" mapstructure:"AtsssInfo"`
}
