/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type DataSetNameAnyOf string

// List of DataSetNameAnyOf 
const (
	DATASETNAMEANYOF_AM DataSetNameAnyOf = "AM"
	DATASETNAMEANYOF_SMF_SEL DataSetNameAnyOf = "SMF_SEL"
	DATASETNAMEANYOF_SMS_SUB DataSetNameAnyOf = "SMS_SUB"
	DATASETNAMEANYOF_SM DataSetNameAnyOf = "SM"
	DATASETNAMEANYOF_TRACE DataSetNameAnyOf = "TRACE"
	DATASETNAMEANYOF_SMS_MNG DataSetNameAnyOf = "SMS_MNG"
	DATASETNAMEANYOF_LCS_PRIVACY DataSetNameAnyOf = "LCS_PRIVACY"
	DATASETNAMEANYOF_LCS_MO DataSetNameAnyOf = "LCS_MO"
	DATASETNAMEANYOF_LCS_BCA DataSetNameAnyOf = "LCS_BCA"
	DATASETNAMEANYOF_V2_X DataSetNameAnyOf = "V2X"
)
