/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type RatTypeAnyOf string

// List of RatTypeAnyOf 
const (
	RATTYPEANYOF_NR RatTypeAnyOf = "NR"
	RATTYPEANYOF_EUTRA RatTypeAnyOf = "EUTRA"
	RATTYPEANYOF_WLAN RatTypeAnyOf = "WLAN"
	RATTYPEANYOF_VIRTUAL RatTypeAnyOf = "VIRTUAL"
	RATTYPEANYOF_NBIOT RatTypeAnyOf = "NBIOT"
	RATTYPEANYOF_WIRELINE RatTypeAnyOf = "WIRELINE"
	RATTYPEANYOF_WIRELINE_CABLE RatTypeAnyOf = "WIRELINE_CABLE"
	RATTYPEANYOF_WIRELINE_BBF RatTypeAnyOf = "WIRELINE_BBF"
	RATTYPEANYOF_LTE_M RatTypeAnyOf = "LTE-M"
	RATTYPEANYOF_NR_U RatTypeAnyOf = "NR_U"
	RATTYPEANYOF_EUTRA_U RatTypeAnyOf = "EUTRA_U"
	RATTYPEANYOF_TRUSTED_N3_GA RatTypeAnyOf = "TRUSTED_N3GA"
	RATTYPEANYOF_TRUSTED_WLAN RatTypeAnyOf = "TRUSTED_WLAN"
	RATTYPEANYOF_UTRA RatTypeAnyOf = "UTRA"
	RATTYPEANYOF_GERA RatTypeAnyOf = "GERA"
)
