/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type TraceDepth string
// enum type
// List of TraceDepth 
const (
	TRACEDEPTH_MINIMUM TraceDepth = "MINIMUM"
	TRACEDEPTH_MEDIUM TraceDepth = "MEDIUM"
	TRACEDEPTH_MAXIMUM TraceDepth = "MAXIMUM"
	TRACEDEPTH_MINIMUM_WO_VENDOR_EXTENSION TraceDepth = "MINIMUM_WO_VENDOR_EXTENSION"
	TRACEDEPTH_MEDIUM_WO_VENDOR_EXTENSION TraceDepth = "MEDIUM_WO_VENDOR_EXTENSION"
	TRACEDEPTH_MAXIMUM_WO_VENDOR_EXTENSION TraceDepth = "MAXIMUM_WO_VENDOR_EXTENSION"
)
