/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type RestrictionType string
// enum type
// List of RestrictionType 
const (
	RESTRICTIONTYPE_ALLOWED_AREAS RestrictionType = "ALLOWED_AREAS"
	RESTRICTIONTYPE_NOT_ALLOWED_AREAS RestrictionType = "NOT_ALLOWED_AREAS"
)
