/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ServiceParameterData struct {


	
	// simple type

	// Identifies an application. 
	

	AppId *string `json:"appId,omitempty" yaml:"appId" bson:"appId" mapstructure:"AppId"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	Snssai *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai" mapstructure:"Snssai"`
 
	

	InterGroupId *string `json:"interGroupId,omitempty" yaml:"interGroupId" bson:"interGroupId" mapstructure:"InterGroupId"`
 
	

	Supi *string `json:"supi,omitempty" yaml:"supi" bson:"supi" mapstructure:"Supi"`

	// string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166. 
	

	UeIpv4 *string `json:"ueIpv4,omitempty" yaml:"ueIpv4" bson:"ueIpv4" mapstructure:"UeIpv4"`

	// string identifying a Ipv6 address formatted according to clause 4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of IETF RFC 5952 shall not be used. 
	

	UeIpv6 *string `json:"ueIpv6,omitempty" yaml:"ueIpv6" bson:"ueIpv6" mapstructure:"UeIpv6"`
 
	

	UeMac *string `json:"ueMac,omitempty" yaml:"ueMac" bson:"ueMac" mapstructure:"UeMac"`
 
	

	AnyUeInd *bool `json:"anyUeInd,omitempty" yaml:"anyUeInd" bson:"anyUeInd" mapstructure:"AnyUeInd"`
 
	

	ParamOverPc5 *string `json:"paramOverPc5,omitempty" yaml:"paramOverPc5" bson:"paramOverPc5" mapstructure:"ParamOverPc5"`
 
	

	ParamOverUu *string `json:"paramOverUu,omitempty" yaml:"paramOverUu" bson:"paramOverUu" mapstructure:"ParamOverUu"`
 
	

	SuppFeat *string `json:"suppFeat,omitempty" yaml:"suppFeat" bson:"suppFeat" mapstructure:"SuppFeat"`
 
	

	ResUri *string `json:"resUri,omitempty" yaml:"resUri" bson:"resUri" mapstructure:"ResUri"`
}
