/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LoggingIntervalMdtAnyOf string

// List of LoggingIntervalMdtAnyOf 
const (
	LOGGINGINTERVALMDTANYOF__128 LoggingIntervalMdtAnyOf = "128"
	LOGGINGINTERVALMDTANYOF__256 LoggingIntervalMdtAnyOf = "256"
	LOGGINGINTERVALMDTANYOF__512 LoggingIntervalMdtAnyOf = "512"
	LOGGINGINTERVALMDTANYOF__1024 LoggingIntervalMdtAnyOf = "1024"
	LOGGINGINTERVALMDTANYOF__2048 LoggingIntervalMdtAnyOf = "2048"
	LOGGINGINTERVALMDTANYOF__3072 LoggingIntervalMdtAnyOf = "3072"
	LOGGINGINTERVALMDTANYOF__4096 LoggingIntervalMdtAnyOf = "4096"
	LOGGINGINTERVALMDTANYOF__6144 LoggingIntervalMdtAnyOf = "6144"
)
