/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type TrafficInfluDataPatch struct {


	
	// simple type

	// Contains the Notification Correlation Id allocated by the NEF for the UP path change notification. 
	

	UpPathChgNotifCorreId *string `json:"upPathChgNotifCorreId,omitempty" yaml:"upPathChgNotifCorreId" bson:"upPathChgNotifCorreId" mapstructure:"UpPathChgNotifCorreId"`

	// Identifies whether an application can be relocated once a location of the application has been selected. 
	

	AppReloInd *bool `json:"appReloInd,omitempty" yaml:"appReloInd" bson:"appReloInd" mapstructure:"AppReloInd"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`

	// Identifies Ethernet packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable. 
	

	EthTrafficFilters *[]EthFlowDescription `json:"ethTrafficFilters,omitempty" yaml:"ethTrafficFilters" bson:"ethTrafficFilters" mapstructure:"EthTrafficFilters"`
 
	

	Snssai *Snssai `json:"snssai,omitempty" yaml:"snssai" bson:"snssai" mapstructure:"Snssai"`
 
	

	InternalGroupId *string `json:"internalGroupId,omitempty" yaml:"internalGroupId" bson:"internalGroupId" mapstructure:"InternalGroupId"`
 
	

	Supi *string `json:"supi,omitempty" yaml:"supi" bson:"supi" mapstructure:"Supi"`

	// Identifies IP packet filters. Either \"trafficFilters\" or \"ethTrafficFilters\" shall be included if applicable. 
	

	TrafficFilters *[]FlowInfo `json:"trafficFilters,omitempty" yaml:"trafficFilters" bson:"trafficFilters" mapstructure:"TrafficFilters"`

	// Identifies the N6 traffic routing requirement. 
	

	TrafficRoutes *[]RouteToLocation `json:"trafficRoutes,omitempty" yaml:"trafficRoutes" bson:"trafficRoutes" mapstructure:"TrafficRoutes"`
 
	

	TraffCorreInd *bool `json:"traffCorreInd,omitempty" yaml:"traffCorreInd" bson:"traffCorreInd" mapstructure:"TraffCorreInd"`
 
	

	ValidStartTime *time.Time `json:"validStartTime,omitempty" yaml:"validStartTime" bson:"validStartTime" mapstructure:"ValidStartTime"`
 
	

	ValidEndTime *time.Time `json:"validEndTime,omitempty" yaml:"validEndTime" bson:"validEndTime" mapstructure:"ValidEndTime"`

	// Identifies the temporal validities for the N6 traffic routing requirement. 
	

	TempValidities *[]TemporalValidity `json:"tempValidities,omitempty" yaml:"tempValidities" bson:"tempValidities" mapstructure:"TempValidities"`
 
	

	NwAreaInfo *NetworkAreaInfo `json:"nwAreaInfo,omitempty" yaml:"nwAreaInfo" bson:"nwAreaInfo" mapstructure:"NwAreaInfo"`
 
	

	UpPathChgNotifUri *string `json:"upPathChgNotifUri,omitempty" yaml:"upPathChgNotifUri" bson:"upPathChgNotifUri" mapstructure:"UpPathChgNotifUri"`
 
	

	Headers *[]string `json:"headers,omitempty" yaml:"headers" bson:"headers" mapstructure:"Headers"`
 
	

	AfAckInd *bool `json:"afAckInd,omitempty" yaml:"afAckInd" bson:"afAckInd" mapstructure:"AfAckInd"`
 
	

	AddrPreserInd *bool `json:"addrPreserInd,omitempty" yaml:"addrPreserInd" bson:"addrPreserInd" mapstructure:"AddrPreserInd"`
}
