/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AuthMethodAnyOf string

// List of AuthMethodAnyOf 
const (
	AUTHMETHODANYOF__5_G_AKA AuthMethodAnyOf = "5G_AKA"
	AUTHMETHODANYOF_EAP_AKA_PRIME AuthMethodAnyOf = "EAP_AKA_PRIME"
	AUTHMETHODANYOF_EAP_TLS AuthMethodAnyOf = "EAP_TLS"
)
