/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type InterFreqTargetInfo struct {


	
	// simple type
 
	

	DlCarrierFreq int32 `json:"dlCarrierFreq" yaml:"dlCarrierFreq" bson:"dlCarrierFreq" mapstructure:"DlCarrierFreq"`
 
	

	CellIdList *[]int32 `json:"cellIdList,omitempty" yaml:"cellIdList" bson:"cellIdList" mapstructure:"CellIdList"`
}
