/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ProvisionedDataSets struct {


	
	// simple type
 
	

	AmData *AccessAndMobilitySubscriptionData `json:"amData,omitempty" yaml:"amData" bson:"amData" mapstructure:"AmData"`
 
	

	SmfSelData *SmfSelectionSubscriptionData `json:"smfSelData,omitempty" yaml:"smfSelData" bson:"smfSelData" mapstructure:"SmfSelData"`
 
	

	SmsSubsData *SmsSubscriptionData `json:"smsSubsData,omitempty" yaml:"smsSubsData" bson:"smsSubsData" mapstructure:"SmsSubsData"`
 
	

	SmData *[]SessionManagementSubscriptionData `json:"smData,omitempty" yaml:"smData" bson:"smData" mapstructure:"SmData"`
 
	

	TraceData *TraceData `json:"traceData,omitempty" yaml:"traceData" bson:"traceData" mapstructure:"TraceData"`
 
	

	SmsMngData *SmsManagementSubscriptionData `json:"smsMngData,omitempty" yaml:"smsMngData" bson:"smsMngData" mapstructure:"SmsMngData"`
 
	

	LcsPrivacyData *LcsPrivacyData `json:"lcsPrivacyData,omitempty" yaml:"lcsPrivacyData" bson:"lcsPrivacyData" mapstructure:"LcsPrivacyData"`
 
	

	LcsMoData *LcsMoData `json:"lcsMoData,omitempty" yaml:"lcsMoData" bson:"lcsMoData" mapstructure:"LcsMoData"`
 
	

	LcsBcaData *LcsBroadcastAssistanceTypesData `json:"lcsBcaData,omitempty" yaml:"lcsBcaData" bson:"lcsBcaData" mapstructure:"LcsBcaData"`
 
	

	V2xData *V2xSubscriptionData `json:"v2xData,omitempty" yaml:"v2xData" bson:"v2xData" mapstructure:"V2xData"`
}
