/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type CollectionPeriodRmmLteMdt string
// enum type
// List of CollectionPeriodRmmLteMdt 
const (
	COLLECTIONPERIODRMMLTEMDT__1024 CollectionPeriodRmmLteMdt = "1024"
	COLLECTIONPERIODRMMLTEMDT__1280 CollectionPeriodRmmLteMdt = "1280"
	COLLECTIONPERIODRMMLTEMDT__2048 CollectionPeriodRmmLteMdt = "2048"
	COLLECTIONPERIODRMMLTEMDT__2560 CollectionPeriodRmmLteMdt = "2560"
	COLLECTIONPERIODRMMLTEMDT__5120 CollectionPeriodRmmLteMdt = "5120"
	COLLECTIONPERIODRMMLTEMDT__10240 CollectionPeriodRmmLteMdt = "10240"
	COLLECTIONPERIODRMMLTEMDT__60000 CollectionPeriodRmmLteMdt = "60000"
)
