/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// DataFilter - Identifies a data filter.
type DataFilter struct {


	
	// simple type
 
	

	DataInd DataInd `json:"dataInd" yaml:"dataInd" bson:"dataInd" mapstructure:"DataInd"`
 
	

	Dnns *[]string `json:"dnns,omitempty" yaml:"dnns" bson:"dnns" mapstructure:"Dnns"`
 
	

	Snssais *[]Snssai `json:"snssais,omitempty" yaml:"snssais" bson:"snssais" mapstructure:"Snssais"`
 
	

	InternalGroupIds *[]string `json:"internalGroupIds,omitempty" yaml:"internalGroupIds" bson:"internalGroupIds" mapstructure:"InternalGroupIds"`
 
	

	Supis *[]string `json:"supis,omitempty" yaml:"supis" bson:"supis" mapstructure:"Supis"`
 
	

	AppIds *[]string `json:"appIds,omitempty" yaml:"appIds" bson:"appIds" mapstructure:"AppIds"`
 
	

	UeIpv4s *[]string `json:"ueIpv4s,omitempty" yaml:"ueIpv4s" bson:"ueIpv4s" mapstructure:"UeIpv4s"`
 
	

	UeIpv6s *[]Ipv6Addr `json:"ueIpv6s,omitempty" yaml:"ueIpv6s" bson:"ueIpv6s" mapstructure:"UeIpv6s"`
 
	

	UeMacs *[]string `json:"ueMacs,omitempty" yaml:"ueMacs" bson:"ueMacs" mapstructure:"UeMacs"`
}
