/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type CagInfo struct {


	
	// simple type
 
	

	AllowedCagList []string `json:"allowedCagList" yaml:"allowedCagList" bson:"allowedCagList" mapstructure:"AllowedCagList"`
 
	

	CagOnlyIndicator *bool `json:"cagOnlyIndicator,omitempty" yaml:"cagOnlyIndicator" bson:"cagOnlyIndicator" mapstructure:"CagOnlyIndicator"`
}
