/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// SponsorConnectivityData - Contains the sponsored data connectivity related information for a sponsor identifier.
type SponsorConnectivityData struct {


	
	// simple type
 
	

	AspIds []string `json:"aspIds" yaml:"aspIds" bson:"aspIds" mapstructure:"AspIds"`
}
