/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EcRestriction struct {


	
	// simple type
 
	

	AfInstanceId string `json:"afInstanceId" yaml:"afInstanceId" bson:"afInstanceId" mapstructure:"AfInstanceId"`
 
	

	ReferenceId int32 `json:"referenceId" yaml:"referenceId" bson:"referenceId" mapstructure:"ReferenceId"`
 
	

	PlmnEcInfos *[]PlmnEcInfo `json:"plmnEcInfos,omitempty" yaml:"plmnEcInfos" bson:"plmnEcInfos" mapstructure:"PlmnEcInfos"`
 
	

	MtcProviderInformation *string `json:"mtcProviderInformation,omitempty" yaml:"mtcProviderInformation" bson:"mtcProviderInformation" mapstructure:"MtcProviderInformation"`
}
