/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type BatteryIndication struct {


	
	// simple type
 
	

	BatteryInd *bool `json:"batteryInd,omitempty" yaml:"batteryInd" bson:"batteryInd" mapstructure:"BatteryInd"`
 
	

	ReplaceableInd *bool `json:"replaceableInd,omitempty" yaml:"replaceableInd" bson:"replaceableInd" mapstructure:"ReplaceableInd"`
 
	

	RechargeableInd *bool `json:"rechargeableInd,omitempty" yaml:"rechargeableInd" bson:"rechargeableInd" mapstructure:"RechargeableInd"`
}
