/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type VnGroupData struct {


	
	// simple type
 
	

	PduSessionTypes *PduSessionTypes `json:"pduSessionTypes,omitempty" yaml:"pduSessionTypes" bson:"pduSessionTypes" mapstructure:"PduSessionTypes"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	SingleNssai *Snssai `json:"singleNssai,omitempty" yaml:"singleNssai" bson:"singleNssai" mapstructure:"SingleNssai"`
 
	

	AppDescriptors *[]AppDescriptor `json:"appDescriptors,omitempty" yaml:"appDescriptors" bson:"appDescriptors" mapstructure:"AppDescriptors"`
}
