/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type TwapId struct {


	
	// simple type
 
	

	SsId string `json:"ssId" yaml:"ssId" bson:"ssId" mapstructure:"SsId"`
 
	

	BssId *string `json:"bssId,omitempty" yaml:"bssId" bson:"bssId" mapstructure:"BssId"`
 
	

	CivicAddress *string `json:"civicAddress,omitempty" yaml:"civicAddress" bson:"civicAddress" mapstructure:"CivicAddress"`
}
