/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


// UpdatedItem - Identifies a fragment of a resource.
type UpdatedItem struct {


	
	// simple type

	// Identifies a fragment (subset of resource data) of a given resource. 
	

	Item string `json:"item" yaml:"item" bson:"item" mapstructure:"Item"`
 
	

	Value interface{} `json:"value" yaml:"value" bson:"value" mapstructure:"Value"`
}
