/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AuthType string
// enum type
// List of AuthType 
const (
	AUTHTYPE__5_G_AKA AuthType = "5G_AKA"
	AUTHTYPE_EAP_AKA_PRIME AuthType = "EAP_AKA_PRIME"
	AUTHTYPE_EAP_TLS AuthType = "EAP_TLS"
)
