/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type AuthMethod string
// enum type
// List of AuthMethod 
const (
	AUTHMETHOD__5_G_AKA AuthMethod = "5G_AKA"
	AUTHMETHOD_EAP_AKA_PRIME AuthMethod = "EAP_AKA_PRIME"
	AUTHMETHOD_EAP_TLS AuthMethod = "EAP_TLS"
)
