/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PfdChangeNotification struct {


	
	// simple type
 
	

	ApplicationId string `json:"applicationId" yaml:"applicationId" bson:"applicationId" mapstructure:"ApplicationId"`
 
	

	RemovalFlag *bool `json:"removalFlag,omitempty" yaml:"removalFlag" bson:"removalFlag" mapstructure:"RemovalFlag"`
 
	

	PartialFlag *bool `json:"partialFlag,omitempty" yaml:"partialFlag" bson:"partialFlag" mapstructure:"PartialFlag"`
 
	

	Pfds *[]PfdContent `json:"pfds,omitempty" yaml:"pfds" bson:"pfds" mapstructure:"Pfds"`
}
