/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PtwParameters struct {


	
	// simple type
 
	

	OperationMode OperationMode `json:"operationMode" yaml:"operationMode" bson:"operationMode" mapstructure:"OperationMode"`
 
	

	PtwValue string `json:"ptwValue" yaml:"ptwValue" bson:"ptwValue" mapstructure:"PtwValue"`
}
