/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

	"time"
)


type SdmSubscription struct {


	
	// simple type
 
	

	NfInstanceId string `json:"nfInstanceId" yaml:"nfInstanceId" bson:"nfInstanceId" mapstructure:"NfInstanceId"`
 
	

	ImplicitUnsubscribe *bool `json:"implicitUnsubscribe,omitempty" yaml:"implicitUnsubscribe" bson:"implicitUnsubscribe" mapstructure:"ImplicitUnsubscribe"`
 
	

	Expires *time.Time `json:"expires,omitempty" yaml:"expires" bson:"expires" mapstructure:"Expires"`
 
	

	CallbackReference string `json:"callbackReference" yaml:"callbackReference" bson:"callbackReference" mapstructure:"CallbackReference"`
 
	

	AmfServiceName *ServiceName `json:"amfServiceName,omitempty" yaml:"amfServiceName" bson:"amfServiceName" mapstructure:"AmfServiceName"`
 
	

	MonitoredResourceUris []string `json:"monitoredResourceUris" yaml:"monitoredResourceUris" bson:"monitoredResourceUris" mapstructure:"MonitoredResourceUris"`
 
	

	SingleNssai *Snssai `json:"singleNssai,omitempty" yaml:"singleNssai" bson:"singleNssai" mapstructure:"SingleNssai"`
 
	

	Dnn *string `json:"dnn,omitempty" yaml:"dnn" bson:"dnn" mapstructure:"Dnn"`
 
	

	SubscriptionId *string `json:"subscriptionId,omitempty" yaml:"subscriptionId" bson:"subscriptionId" mapstructure:"SubscriptionId"`
 
	

	PlmnId *PlmnId `json:"plmnId,omitempty" yaml:"plmnId" bson:"plmnId" mapstructure:"PlmnId"`
 
	

	ImmediateReport *bool `json:"immediateReport,omitempty" yaml:"immediateReport" bson:"immediateReport" mapstructure:"ImmediateReport"`
 
	

	Report *SubscriptionDataSets `json:"report,omitempty" yaml:"report" bson:"report" mapstructure:"Report"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
 
	

	ContextInfo *ContextInfo `json:"contextInfo,omitempty" yaml:"contextInfo" bson:"contextInfo" mapstructure:"ContextInfo"`
}
