/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type EventForMdt string
// enum type
// List of EventForMdt 
const (
	EVENTFORMDT_OUT_OF_COVERAG EventForMdt = "OUT_OF_COVERAG"
	EVENTFORMDT_A2_EVENT EventForMdt = "A2_EVENT"
)
