/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type MdtUserConsent string
// enum type
// List of MdtUserConsent 
const (
	MDTUSERCONSENT_NOT_GIVEN MdtUserConsent = "CONSENT_NOT_GIVEN"
	MDTUSERCONSENT_GIVEN MdtUserConsent = "CONSENT_GIVEN"
)
