/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type LoggingDurationNrMdt string
// enum type
// List of LoggingDurationNrMdt 
const (
	LOGGINGDURATIONNRMDT__600 LoggingDurationNrMdt = "600"
	LOGGINGDURATIONNRMDT__1200 LoggingDurationNrMdt = "1200"
	LOGGINGDURATIONNRMDT__2400 LoggingDurationNrMdt = "2400"
	LOGGINGDURATIONNRMDT__3600 LoggingDurationNrMdt = "3600"
	LOGGINGDURATIONNRMDT__5400 LoggingDurationNrMdt = "5400"
	LOGGINGDURATIONNRMDT__7200 LoggingDurationNrMdt = "7200"
)
