/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DomainNameProtocol string
// enum type
// List of DomainNameProtocol 
const (
	DOMAINNAMEPROTOCOL_DNS_QNAME DomainNameProtocol = "DNS_QNAME"
	DOMAINNAMEPROTOCOL_TLS_SNI DomainNameProtocol = "TLS_SNI"
	DOMAINNAMEPROTOCOL_TLS_SAN DomainNameProtocol = "TLS_SAN"
	DOMAINNAMEPROTOCOL_TSL_SCN DomainNameProtocol = "TSL_SCN"
)
