/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PatchOperationAnyOf string

// List of PatchOperationAnyOf 
const (
	PATCHOPERATIONANYOF_ADD PatchOperationAnyOf = "add"
	PATCHOPERATIONANYOF_COPY PatchOperationAnyOf = "copy"
	PATCHOPERATIONANYOF_MOVE PatchOperationAnyOf = "move"
	PATCHOPERATIONANYOF_REMOVE PatchOperationAnyOf = "remove"
	PATCHOPERATIONANYOF_REPLACE PatchOperationAnyOf = "replace"
	PATCHOPERATIONANYOF_TEST PatchOperationAnyOf = "test"
)
