/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ReportIntervalMdt string
// enum type
// List of ReportIntervalMdt 
const (
	REPORTINTERVALMDT__120 ReportIntervalMdt = "120"
	REPORTINTERVALMDT__240 ReportIntervalMdt = "240"
	REPORTINTERVALMDT__480 ReportIntervalMdt = "480"
	REPORTINTERVALMDT__640 ReportIntervalMdt = "640"
	REPORTINTERVALMDT__1024 ReportIntervalMdt = "1024"
	REPORTINTERVALMDT__2048 ReportIntervalMdt = "2048"
	REPORTINTERVALMDT__5120 ReportIntervalMdt = "5120"
	REPORTINTERVALMDT__10240 ReportIntervalMdt = "10240"
	REPORTINTERVALMDT__60000 ReportIntervalMdt = "60000"
	REPORTINTERVALMDT__360000 ReportIntervalMdt = "360000"
	REPORTINTERVALMDT__720000 ReportIntervalMdt = "720000"
	REPORTINTERVALMDT__1800000 ReportIntervalMdt = "1800000"
	REPORTINTERVALMDT__3600000 ReportIntervalMdt = "3600000"
)
