/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data). The API version is defined in 3GPP TS 29.504. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SupportedGadShapesAnyOf string

// List of SupportedGadShapesAnyOf 
const (
	SUPPORTEDGADSHAPESANYOF_POINT SupportedGadShapesAnyOf = "POINT"
	SUPPORTEDGADSHAPESANYOF_POINT_UNCERTAINTY_CIRCLE SupportedGadShapesAnyOf = "POINT_UNCERTAINTY_CIRCLE"
	SUPPORTEDGADSHAPESANYOF_POINT_UNCERTAINTY_ELLIPSE SupportedGadShapesAnyOf = "POINT_UNCERTAINTY_ELLIPSE"
	SUPPORTEDGADSHAPESANYOF_POLYGON SupportedGadShapesAnyOf = "POLYGON"
	SUPPORTEDGADSHAPESANYOF_POINT_ALTITUDE SupportedGadShapesAnyOf = "POINT_ALTITUDE"
	SUPPORTEDGADSHAPESANYOF_POINT_ALTITUDE_UNCERTAINTY SupportedGadShapesAnyOf = "POINT_ALTITUDE_UNCERTAINTY"
	SUPPORTEDGADSHAPESANYOF_ELLIPSOID_ARC SupportedGadShapesAnyOf = "ELLIPSOID_ARC"
)
