/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type FlowInfo struct {


	
	// simple type

	// Indicates the IP flow. 
	

	FlowId int32 `json:"flowId" yaml:"flowId" bson:"flowId" mapstructure:"FlowId"`

	// Indicates the packet filters of the IP flow. Refer to subclause 5.3.8 of 3GPP TS 29.214 for encoding. It shall contain UL and/or DL IP flow description. 
	

	FlowDescriptions *[]string `json:"flowDescriptions,omitempty" yaml:"flowDescriptions" bson:"flowDescriptions" mapstructure:"FlowDescriptions"`
}
