/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ServiceParameterDataPatch struct {


	
	// simple type
 
	

	ParamOverPc5 *string `json:"paramOverPc5,omitempty" yaml:"paramOverPc5" bson:"paramOverPc5" mapstructure:"ParamOverPc5"`
 
	

	ParamOverUu *string `json:"paramOverUu,omitempty" yaml:"paramOverUu" bson:"paramOverUu" mapstructure:"ParamOverUu"`
}
