/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type ChangeItem struct {


	
	// simple type
 
	

	Op ChangeType `json:"op" yaml:"op" bson:"op" mapstructure:"Op"`
 
	

	Path string `json:"path" yaml:"path" bson:"path" mapstructure:"Path"`
 
	

	From *string `json:"from,omitempty" yaml:"from" bson:"from" mapstructure:"From"`
 
	

	OrigValue *interface{} `json:"origValue,omitempty" yaml:"origValue" bson:"origValue" mapstructure:"OrigValue"`
 
	

	NewValue *interface{} `json:"newValue,omitempty" yaml:"newValue" bson:"newValue" mapstructure:"NewValue"`
}
