/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type UpIntegrity string
// enum type
// List of UpIntegrity 
const (
	UPINTEGRITY_REQUIRED UpIntegrity = "REQUIRED"
	UPINTEGRITY_PREFERRED UpIntegrity = "PREFERRED"
	UPINTEGRITY_NOT_NEEDED UpIntegrity = "NOT_NEEDED"
)
