/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DataSetName string
// enum type
// List of DataSetName 
const (
	DATASETNAME_AM DataSetName = "AM"
	DATASETNAME_SMF_SEL DataSetName = "SMF_SEL"
	DATASETNAME_SMS_SUB DataSetName = "SMS_SUB"
	DATASETNAME_SM DataSetName = "SM"
	DATASETNAME_TRACE DataSetName = "TRACE"
	DATASETNAME_SMS_MNG DataSetName = "SMS_MNG"
	DATASETNAME_LCS_PRIVACY DataSetName = "LCS_PRIVACY"
	DATASETNAME_LCS_MO DataSetName = "LCS_MO"
	DATASETNAME_LCS_BCA DataSetName = "LCS_BCA"
	DATASETNAME_V2_X DataSetName = "V2X"
)
