/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PresenceState string
// enum type
// List of PresenceState 
const (
	PRESENCESTATE_IN_AREA PresenceState = "IN_AREA"
	PRESENCESTATE_OUT_OF_AREA PresenceState = "OUT_OF_AREA"
	PRESENCESTATE_UNKNOWN PresenceState = "UNKNOWN"
	PRESENCESTATE_INACTIVE PresenceState = "INACTIVE"
)
