/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type PpData struct {


	
	// simple type
 
	

	CommunicationCharacteristics *CommunicationCharacteristics `json:"communicationCharacteristics,omitempty" yaml:"communicationCharacteristics" bson:"communicationCharacteristics" mapstructure:"CommunicationCharacteristics"`
 
	

	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
 
	

	ExpectedUeBehaviourParameters *ExpectedUeBehaviour `json:"expectedUeBehaviourParameters,omitempty" yaml:"expectedUeBehaviourParameters" bson:"expectedUeBehaviourParameters" mapstructure:"ExpectedUeBehaviourParameters"`
 
	

	EcRestriction *EcRestriction `json:"ecRestriction,omitempty" yaml:"ecRestriction" bson:"ecRestriction" mapstructure:"EcRestriction"`
 
	

	AcsInfo *AcsInfo1 `json:"acsInfo,omitempty" yaml:"acsInfo" bson:"acsInfo" mapstructure:"AcsInfo"`
 
	

	StnSr *string `json:"stnSr,omitempty" yaml:"stnSr" bson:"stnSr" mapstructure:"StnSr"`
 
	

	LcsPrivacy *LcsPrivacy `json:"lcsPrivacy,omitempty" yaml:"lcsPrivacy" bson:"lcsPrivacy" mapstructure:"LcsPrivacy"`
 
	

	SorInfo *SorInfo `json:"sorInfo,omitempty" yaml:"sorInfo" bson:"sorInfo" mapstructure:"SorInfo"`
}
