/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type VgmlcAddress struct {


	
	// simple type
 
	

	VgmlcAddressIpv4 *string `json:"vgmlcAddressIpv4,omitempty" yaml:"vgmlcAddressIpv4" bson:"vgmlcAddressIpv4" mapstructure:"VgmlcAddressIpv4"`
 
	

	VgmlcAddressIpv6 *Ipv6Addr `json:"vgmlcAddressIpv6,omitempty" yaml:"vgmlcAddressIpv6" bson:"vgmlcAddressIpv6" mapstructure:"VgmlcAddressIpv6"`

	// Fully Qualified Domain Name 
	

	VgmlcFqdn *string `json:"vgmlcFqdn,omitempty" yaml:"vgmlcFqdn" bson:"vgmlcFqdn" mapstructure:"VgmlcFqdn"`
}
