/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (

)


type DataChangeNotify struct {


	
	// simple type
 
	

	OriginalCallbackReference *[]string `json:"originalCallbackReference,omitempty" yaml:"originalCallbackReference" bson:"originalCallbackReference" mapstructure:"OriginalCallbackReference"`
 
	

	UeId *string `json:"ueId,omitempty" yaml:"ueId" bson:"ueId" mapstructure:"UeId"`
 
	

	NotifyItems *[]NotifyItem `json:"notifyItems,omitempty" yaml:"notifyItems" bson:"notifyItems" mapstructure:"NotifyItems"`
 
	

	SdmSubscription *SdmSubscription `json:"sdmSubscription,omitempty" yaml:"sdmSubscription" bson:"sdmSubscription" mapstructure:"SdmSubscription"`
 
	

	AdditionalSdmSubscriptions *[]SdmSubscription `json:"additionalSdmSubscriptions,omitempty" yaml:"additionalSdmSubscriptions" bson:"additionalSdmSubscriptions" mapstructure:"AdditionalSdmSubscriptions"`
 
	

	SubscriptionDataSubscriptions *[]SubscriptionDataSubscriptions `json:"subscriptionDataSubscriptions,omitempty" yaml:"subscriptionDataSubscriptions" bson:"subscriptionDataSubscriptions" mapstructure:"SubscriptionDataSubscriptions"`
}
